//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.financial.accountsPayable.input.voucherAndAdjustmentEntry.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctapi/services/ctDynamicsSL/voucherAndAdjustmentEntry.asmx")]
        public string client_financial_accountsPayable_input_voucherAndAdjustmentEntry_ctDynamicsSL_financial_accountsPayable_input_voucherAndAdjustmentEntry_voucherAndAdjustmentEntry {
            get {
                return ((string)(this["client_financial_accountsPayable_input_voucherAndAdjustmentEntry_ctDynamicsSL_fin" +
                    "ancial_accountsPayable_input_voucherAndAdjustmentEntry_voucherAndAdjustmentEntry" +
                    ""]));
            }
        }
    }
}
