//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace client.orderManagement.maintenance.customerContacts.ctDynamicsSL.orderManagement.maintenance.customerContacts {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="customerContactsSoap", Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class customerContacts : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback aboutOperationCompleted;
        
        private ctDynamicsSLHeader ctDynamicsSLHeaderValueField;
        
        private System.Threading.SendOrPostCallback getCustContactsByCustIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactByExactIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateCustIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScreenByCustIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewscreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback editScreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback editNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback editNoteAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback editCustContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback editCustContactAsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback editCustContactAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback editCustContactAsDataSetAsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewCustContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewCustContactAsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactsAsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactsAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustContactsAsDataSetAsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback pingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public customerContacts() {
            this.Url = global::client.orderManagement.maintenance.customerContacts.Properties.Settings.Default.client_orderManagement_maintenance_customerContacts_ctDynamicsSL_orderManagement_maintenance_customerContacts_customerContacts;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ctDynamicsSLHeader ctDynamicsSLHeaderValue {
            get {
                return this.ctDynamicsSLHeaderValueField;
            }
            set {
                this.ctDynamicsSLHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event aboutCompletedEventHandler aboutCompleted;
        
        /// <remarks/>
        public event getCustContactsByCustIDCompletedEventHandler getCustContactsByCustIDCompleted;
        
        /// <remarks/>
        public event getCustContactsByIDCompletedEventHandler getCustContactsByIDCompleted;
        
        /// <remarks/>
        public event getCustContactByExactIDCompletedEventHandler getCustContactByExactIDCompleted;
        
        /// <remarks/>
        public event validateCustIDCompletedEventHandler validateCustIDCompleted;
        
        /// <remarks/>
        public event getScreenByCustIDCompletedEventHandler getScreenByCustIDCompleted;
        
        /// <remarks/>
        public event getNewscreenCompletedEventHandler getNewscreenCompleted;
        
        /// <remarks/>
        public event editScreenCompletedEventHandler editScreenCompleted;
        
        /// <remarks/>
        public event editNoteCompletedEventHandler editNoteCompleted;
        
        /// <remarks/>
        public event editNoteAsDataSetCompletedEventHandler editNoteAsDataSetCompleted;
        
        /// <remarks/>
        public event editCustContactCompletedEventHandler editCustContactCompleted;
        
        /// <remarks/>
        public event editCustContactAsJSONCompletedEventHandler editCustContactAsJSONCompleted;
        
        /// <remarks/>
        public event editCustContactAsDataSetCompletedEventHandler editCustContactAsDataSetCompleted;
        
        /// <remarks/>
        public event editCustContactAsDataSetAsJSONCompletedEventHandler editCustContactAsDataSetAsJSONCompleted;
        
        /// <remarks/>
        public event getNewCustContactCompletedEventHandler getNewCustContactCompleted;
        
        /// <remarks/>
        public event getNewCustContactAsJSONCompletedEventHandler getNewCustContactAsJSONCompleted;
        
        /// <remarks/>
        public event getCustContactsCompletedEventHandler getCustContactsCompleted;
        
        /// <remarks/>
        public event getCustContactsAsJSONCompletedEventHandler getCustContactsAsJSONCompleted;
        
        /// <remarks/>
        public event getCustContactsAsDataSetCompletedEventHandler getCustContactsAsDataSetCompleted;
        
        /// <remarks/>
        public event getCustContactsAsDataSetAsJSONCompletedEventHandler getCustContactsAsDataSetAsJSONCompleted;
        
        /// <remarks/>
        public event pingCompletedEventHandler pingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/about", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string about() {
            object[] results = this.Invoke("about", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aboutAsync() {
            this.aboutAsync(null);
        }
        
        /// <remarks/>
        public void aboutAsync(object userState) {
            if ((this.aboutOperationCompleted == null)) {
                this.aboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaboutOperationCompleted);
            }
            this.InvokeAsync("about", new object[0], this.aboutOperationCompleted, userState);
        }
        
        private void OnaboutOperationCompleted(object arg) {
            if ((this.aboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aboutCompleted(this, new aboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactsByCustID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact[] getCustContactsByCustID(string custID) {
            object[] results = this.Invoke("getCustContactsByCustID", new object[] {
                        custID});
            return ((CustContact[])(results[0]));
        }
        
        /// <remarks/>
        public void getCustContactsByCustIDAsync(string custID) {
            this.getCustContactsByCustIDAsync(custID, null);
        }
        
        /// <remarks/>
        public void getCustContactsByCustIDAsync(string custID, object userState) {
            if ((this.getCustContactsByCustIDOperationCompleted == null)) {
                this.getCustContactsByCustIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsByCustIDOperationCompleted);
            }
            this.InvokeAsync("getCustContactsByCustID", new object[] {
                        custID}, this.getCustContactsByCustIDOperationCompleted, userState);
        }
        
        private void OngetCustContactsByCustIDOperationCompleted(object arg) {
            if ((this.getCustContactsByCustIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsByCustIDCompleted(this, new getCustContactsByCustIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactsByID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact[] getCustContactsByID(string custID, string contactID) {
            object[] results = this.Invoke("getCustContactsByID", new object[] {
                        custID,
                        contactID});
            return ((CustContact[])(results[0]));
        }
        
        /// <remarks/>
        public void getCustContactsByIDAsync(string custID, string contactID) {
            this.getCustContactsByIDAsync(custID, contactID, null);
        }
        
        /// <remarks/>
        public void getCustContactsByIDAsync(string custID, string contactID, object userState) {
            if ((this.getCustContactsByIDOperationCompleted == null)) {
                this.getCustContactsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsByIDOperationCompleted);
            }
            this.InvokeAsync("getCustContactsByID", new object[] {
                        custID,
                        contactID}, this.getCustContactsByIDOperationCompleted, userState);
        }
        
        private void OngetCustContactsByIDOperationCompleted(object arg) {
            if ((this.getCustContactsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsByIDCompleted(this, new getCustContactsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactByExactID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact getCustContactByExactID(string custID, string contactID) {
            object[] results = this.Invoke("getCustContactByExactID", new object[] {
                        custID,
                        contactID});
            return ((CustContact)(results[0]));
        }
        
        /// <remarks/>
        public void getCustContactByExactIDAsync(string custID, string contactID) {
            this.getCustContactByExactIDAsync(custID, contactID, null);
        }
        
        /// <remarks/>
        public void getCustContactByExactIDAsync(string custID, string contactID, object userState) {
            if ((this.getCustContactByExactIDOperationCompleted == null)) {
                this.getCustContactByExactIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactByExactIDOperationCompleted);
            }
            this.InvokeAsync("getCustContactByExactID", new object[] {
                        custID,
                        contactID}, this.getCustContactByExactIDOperationCompleted, userState);
        }
        
        private void OngetCustContactByExactIDOperationCompleted(object arg) {
            if ((this.getCustContactByExactIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactByExactIDCompleted(this, new getCustContactByExactIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/validateCustID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public genericReturn validateCustID(string custID, bool requireActive) {
            object[] results = this.Invoke("validateCustID", new object[] {
                        custID,
                        requireActive});
            return ((genericReturn)(results[0]));
        }
        
        /// <remarks/>
        public void validateCustIDAsync(string custID, bool requireActive) {
            this.validateCustIDAsync(custID, requireActive, null);
        }
        
        /// <remarks/>
        public void validateCustIDAsync(string custID, bool requireActive, object userState) {
            if ((this.validateCustIDOperationCompleted == null)) {
                this.validateCustIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateCustIDOperationCompleted);
            }
            this.InvokeAsync("validateCustID", new object[] {
                        custID,
                        requireActive}, this.validateCustIDOperationCompleted, userState);
        }
        
        private void OnvalidateCustIDOperationCompleted(object arg) {
            if ((this.validateCustIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateCustIDCompleted(this, new validateCustIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getScreenByCustID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen getScreenByCustID(string custID) {
            object[] results = this.Invoke("getScreenByCustID", new object[] {
                        custID});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void getScreenByCustIDAsync(string custID) {
            this.getScreenByCustIDAsync(custID, null);
        }
        
        /// <remarks/>
        public void getScreenByCustIDAsync(string custID, object userState) {
            if ((this.getScreenByCustIDOperationCompleted == null)) {
                this.getScreenByCustIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScreenByCustIDOperationCompleted);
            }
            this.InvokeAsync("getScreenByCustID", new object[] {
                        custID}, this.getScreenByCustIDOperationCompleted, userState);
        }
        
        private void OngetScreenByCustIDOperationCompleted(object arg) {
            if ((this.getScreenByCustIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScreenByCustIDCompleted(this, new getScreenByCustIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewscreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen getNewscreen(screen inTemplate) {
            object[] results = this.Invoke("getNewscreen", new object[] {
                        inTemplate});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void getNewscreenAsync(screen inTemplate) {
            this.getNewscreenAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewscreenAsync(screen inTemplate, object userState) {
            if ((this.getNewscreenOperationCompleted == null)) {
                this.getNewscreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewscreenOperationCompleted);
            }
            this.InvokeAsync("getNewscreen", new object[] {
                        inTemplate}, this.getNewscreenOperationCompleted, userState);
        }
        
        private void OngetNewscreenOperationCompleted(object arg) {
            if ((this.getNewscreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewscreenCompleted(this, new getNewscreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editScreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen editScreen(string actionType, screen inScreen) {
            object[] results = this.Invoke("editScreen", new object[] {
                        actionType,
                        inScreen});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void editScreenAsync(string actionType, screen inScreen) {
            this.editScreenAsync(actionType, inScreen, null);
        }
        
        /// <remarks/>
        public void editScreenAsync(string actionType, screen inScreen, object userState) {
            if ((this.editScreenOperationCompleted == null)) {
                this.editScreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditScreenOperationCompleted);
            }
            this.InvokeAsync("editScreen", new object[] {
                        actionType,
                        inScreen}, this.editScreenOperationCompleted, userState);
        }
        
        private void OneditScreenOperationCompleted(object arg) {
            if ((this.editScreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editScreenCompleted(this, new editScreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editNote", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Snote editNote(string actionType, Snote inSnote) {
            object[] results = this.Invoke("editNote", new object[] {
                        actionType,
                        inSnote});
            return ((Snote)(results[0]));
        }
        
        /// <remarks/>
        public void editNoteAsync(string actionType, Snote inSnote) {
            this.editNoteAsync(actionType, inSnote, null);
        }
        
        /// <remarks/>
        public void editNoteAsync(string actionType, Snote inSnote, object userState) {
            if ((this.editNoteOperationCompleted == null)) {
                this.editNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditNoteOperationCompleted);
            }
            this.InvokeAsync("editNote", new object[] {
                        actionType,
                        inSnote}, this.editNoteOperationCompleted, userState);
        }
        
        private void OneditNoteOperationCompleted(object arg) {
            if ((this.editNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editNoteCompleted(this, new editNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editNoteAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet editNoteAsDataSet(string actionType, Snote inSnote) {
            object[] results = this.Invoke("editNoteAsDataSet", new object[] {
                        actionType,
                        inSnote});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void editNoteAsDataSetAsync(string actionType, Snote inSnote) {
            this.editNoteAsDataSetAsync(actionType, inSnote, null);
        }
        
        /// <remarks/>
        public void editNoteAsDataSetAsync(string actionType, Snote inSnote, object userState) {
            if ((this.editNoteAsDataSetOperationCompleted == null)) {
                this.editNoteAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditNoteAsDataSetOperationCompleted);
            }
            this.InvokeAsync("editNoteAsDataSet", new object[] {
                        actionType,
                        inSnote}, this.editNoteAsDataSetOperationCompleted, userState);
        }
        
        private void OneditNoteAsDataSetOperationCompleted(object arg) {
            if ((this.editNoteAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editNoteAsDataSetCompleted(this, new editNoteAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editCustContact", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact editCustContact(string actionType, CustContact inItem) {
            object[] results = this.Invoke("editCustContact", new object[] {
                        actionType,
                        inItem});
            return ((CustContact)(results[0]));
        }
        
        /// <remarks/>
        public void editCustContactAsync(string actionType, CustContact inItem) {
            this.editCustContactAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editCustContactAsync(string actionType, CustContact inItem, object userState) {
            if ((this.editCustContactOperationCompleted == null)) {
                this.editCustContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditCustContactOperationCompleted);
            }
            this.InvokeAsync("editCustContact", new object[] {
                        actionType,
                        inItem}, this.editCustContactOperationCompleted, userState);
        }
        
        private void OneditCustContactOperationCompleted(object arg) {
            if ((this.editCustContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editCustContactCompleted(this, new editCustContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editCustContactAsJSON", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string editCustContactAsJSON(string actionType, CustContact inItem) {
            object[] results = this.Invoke("editCustContactAsJSON", new object[] {
                        actionType,
                        inItem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void editCustContactAsJSONAsync(string actionType, CustContact inItem) {
            this.editCustContactAsJSONAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editCustContactAsJSONAsync(string actionType, CustContact inItem, object userState) {
            if ((this.editCustContactAsJSONOperationCompleted == null)) {
                this.editCustContactAsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditCustContactAsJSONOperationCompleted);
            }
            this.InvokeAsync("editCustContactAsJSON", new object[] {
                        actionType,
                        inItem}, this.editCustContactAsJSONOperationCompleted, userState);
        }
        
        private void OneditCustContactAsJSONOperationCompleted(object arg) {
            if ((this.editCustContactAsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editCustContactAsJSONCompleted(this, new editCustContactAsJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editCustContactAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet editCustContactAsDataSet(string actionType, CustContact inItem) {
            object[] results = this.Invoke("editCustContactAsDataSet", new object[] {
                        actionType,
                        inItem});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void editCustContactAsDataSetAsync(string actionType, CustContact inItem) {
            this.editCustContactAsDataSetAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editCustContactAsDataSetAsync(string actionType, CustContact inItem, object userState) {
            if ((this.editCustContactAsDataSetOperationCompleted == null)) {
                this.editCustContactAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditCustContactAsDataSetOperationCompleted);
            }
            this.InvokeAsync("editCustContactAsDataSet", new object[] {
                        actionType,
                        inItem}, this.editCustContactAsDataSetOperationCompleted, userState);
        }
        
        private void OneditCustContactAsDataSetOperationCompleted(object arg) {
            if ((this.editCustContactAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editCustContactAsDataSetCompleted(this, new editCustContactAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editCustContactAsDataSetA" +
            "sJSON", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string editCustContactAsDataSetAsJSON(string actionType, CustContact inItem) {
            object[] results = this.Invoke("editCustContactAsDataSetAsJSON", new object[] {
                        actionType,
                        inItem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void editCustContactAsDataSetAsJSONAsync(string actionType, CustContact inItem) {
            this.editCustContactAsDataSetAsJSONAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editCustContactAsDataSetAsJSONAsync(string actionType, CustContact inItem, object userState) {
            if ((this.editCustContactAsDataSetAsJSONOperationCompleted == null)) {
                this.editCustContactAsDataSetAsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditCustContactAsDataSetAsJSONOperationCompleted);
            }
            this.InvokeAsync("editCustContactAsDataSetAsJSON", new object[] {
                        actionType,
                        inItem}, this.editCustContactAsDataSetAsJSONOperationCompleted, userState);
        }
        
        private void OneditCustContactAsDataSetAsJSONOperationCompleted(object arg) {
            if ((this.editCustContactAsDataSetAsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editCustContactAsDataSetAsJSONCompleted(this, new editCustContactAsDataSetAsJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewCustContact", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact getNewCustContact(CustContact inTemplate) {
            object[] results = this.Invoke("getNewCustContact", new object[] {
                        inTemplate});
            return ((CustContact)(results[0]));
        }
        
        /// <remarks/>
        public void getNewCustContactAsync(CustContact inTemplate) {
            this.getNewCustContactAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewCustContactAsync(CustContact inTemplate, object userState) {
            if ((this.getNewCustContactOperationCompleted == null)) {
                this.getNewCustContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewCustContactOperationCompleted);
            }
            this.InvokeAsync("getNewCustContact", new object[] {
                        inTemplate}, this.getNewCustContactOperationCompleted, userState);
        }
        
        private void OngetNewCustContactOperationCompleted(object arg) {
            if ((this.getNewCustContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewCustContactCompleted(this, new getNewCustContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewCustContactAsJSON", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNewCustContactAsJSON(CustContact inTemplate) {
            object[] results = this.Invoke("getNewCustContactAsJSON", new object[] {
                        inTemplate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNewCustContactAsJSONAsync(CustContact inTemplate) {
            this.getNewCustContactAsJSONAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewCustContactAsJSONAsync(CustContact inTemplate, object userState) {
            if ((this.getNewCustContactAsJSONOperationCompleted == null)) {
                this.getNewCustContactAsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewCustContactAsJSONOperationCompleted);
            }
            this.InvokeAsync("getNewCustContactAsJSON", new object[] {
                        inTemplate}, this.getNewCustContactAsJSONOperationCompleted, userState);
        }
        
        private void OngetNewCustContactAsJSONOperationCompleted(object arg) {
            if ((this.getNewCustContactAsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewCustContactAsJSONCompleted(this, new getNewCustContactAsJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContacts", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustContact[] getCustContacts(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getCustContacts", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((CustContact[])(results[0]));
        }
        
        /// <remarks/>
        public void getCustContactsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getCustContactsAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getCustContactsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getCustContactsOperationCompleted == null)) {
                this.getCustContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsOperationCompleted);
            }
            this.InvokeAsync("getCustContacts", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getCustContactsOperationCompleted, userState);
        }
        
        private void OngetCustContactsOperationCompleted(object arg) {
            if ((this.getCustContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsCompleted(this, new getCustContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactsAsJSON", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getCustContactsAsJSON(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.Invoke("getCustContactsAsJSON", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
        }
        
        /// <remarks/>
        public void getCustContactsAsJSONAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getCustContactsAsJSONAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getCustContactsAsJSONAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getCustContactsAsJSONOperationCompleted == null)) {
                this.getCustContactsAsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsAsJSONOperationCompleted);
            }
            this.InvokeAsync("getCustContactsAsJSON", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getCustContactsAsJSONOperationCompleted, userState);
        }
        
        private void OngetCustContactsAsJSONOperationCompleted(object arg) {
            if ((this.getCustContactsAsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsAsJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactsAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustContactsAsDataSet(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getCustContactsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCustContactsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getCustContactsAsDataSetAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getCustContactsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getCustContactsAsDataSetOperationCompleted == null)) {
                this.getCustContactsAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsAsDataSetOperationCompleted);
            }
            this.InvokeAsync("getCustContactsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getCustContactsAsDataSetOperationCompleted, userState);
        }
        
        private void OngetCustContactsAsDataSetOperationCompleted(object arg) {
            if ((this.getCustContactsAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsAsDataSetCompleted(this, new getCustContactsAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getCustContactsAsDataSetA" +
            "sJSON", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getCustContactsAsDataSetAsJSON(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.Invoke("getCustContactsAsDataSetAsJSON", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
        }
        
        /// <remarks/>
        public void getCustContactsAsDataSetAsJSONAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getCustContactsAsDataSetAsJSONAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getCustContactsAsDataSetAsJSONAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getCustContactsAsDataSetAsJSONOperationCompleted == null)) {
                this.getCustContactsAsDataSetAsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustContactsAsDataSetAsJSONOperationCompleted);
            }
            this.InvokeAsync("getCustContactsAsDataSetAsJSON", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getCustContactsAsDataSetAsJSONOperationCompleted, userState);
        }
        
        private void OngetCustContactsAsDataSetAsJSONOperationCompleted(object arg) {
            if ((this.getCustContactsAsDataSetAsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustContactsAsDataSetAsJSONCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/ping", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ping(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            object[] results = this.Invoke("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            this.pingAsync(pingType, siteID, siteKey, licenseKey, licenseName, licenseExpiration, softwareName, null);
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName, object userState) {
            if ((this.pingOperationCompleted == null)) {
                this.pingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpingOperationCompleted);
            }
            this.InvokeAsync("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName}, this.pingOperationCompleted, userState);
        }
        
        private void OnpingOperationCompleted(object arg) {
            if ((this.pingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pingCompleted(this, new pingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL", IsNullable=false)]
    public partial class ctDynamicsSLHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string licenseKeyField;
        
        private string licenseNameField;
        
        private string licenseExpirationField;
        
        private string softwareNameField;
        
        private string siteIDField;
        
        private string siteKeyField;
        
        private string userNameField;
        
        private string cpnyIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string licenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        public string licenseName {
            get {
                return this.licenseNameField;
            }
            set {
                this.licenseNameField = value;
            }
        }
        
        /// <remarks/>
        public string licenseExpiration {
            get {
                return this.licenseExpirationField;
            }
            set {
                this.licenseExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string softwareName {
            get {
                return this.softwareNameField;
            }
            set {
                this.softwareNameField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteKey {
            get {
                return this.siteKeyField;
            }
            set {
                this.siteKeyField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string cpnyID {
            get {
                return this.cpnyIDField;
            }
            set {
                this.cpnyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class nameValuePairs {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class Snote {
        
        private string errorMessageField;
        
        private string notesField;
        
        private int resultCodeField;
        
        private System.DateTime dtRevisedDateField;
        
        private int nIDField;
        
        private string sLevelNameField;
        
        private string sTableNameField;
        
        private string sNoteTextField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtRevisedDate {
            get {
                return this.dtRevisedDateField;
            }
            set {
                this.dtRevisedDateField = value;
            }
        }
        
        /// <remarks/>
        public int nID {
            get {
                return this.nIDField;
            }
            set {
                this.nIDField = value;
            }
        }
        
        /// <remarks/>
        public string sLevelName {
            get {
                return this.sLevelNameField;
            }
            set {
                this.sLevelNameField = value;
            }
        }
        
        /// <remarks/>
        public string sTableName {
            get {
                return this.sTableNameField;
            }
            set {
                this.sTableNameField = value;
            }
        }
        
        /// <remarks/>
        public string sNoteText {
            get {
                return this.sNoteTextField;
            }
            set {
                this.sNoteTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class screen {
        
        private string myCustIDField;
        
        private CustContact[] myCustContactsField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string myCustID {
            get {
                return this.myCustIDField;
            }
            set {
                this.myCustIDField = value;
            }
        }
        
        /// <remarks/>
        public CustContact[] myCustContacts {
            get {
                return this.myCustContactsField;
            }
            set {
                this.myCustContactsField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class CustContact {
        
        private string errorMessageField;
        
        private string notesField;
        
        private int resultCodeField;
        
        private string addr1Field;
        
        private string addr2Field;
        
        private string cityField;
        
        private string contactIDField;
        
        private string countryField;
        
        private System.DateTime crtd_DateTimeField;
        
        private string crtd_ProgField;
        
        private string crtd_UserField;
        
        private string custIDField;
        
        private string emailAddrField;
        
        private string faxField;
        
        private System.DateTime lUpd_DateTimeField;
        
        private string lUpd_ProgField;
        
        private string lUpd_UserField;
        
        private string nameField;
        
        private int noteIDField;
        
        private double orderLimitField;
        
        private string phoneField;
        
        private double pOReqdAmtField;
        
        private string s4Future01Field;
        
        private string s4Future02Field;
        
        private double s4Future03Field;
        
        private double s4Future04Field;
        
        private double s4Future05Field;
        
        private double s4Future06Field;
        
        private System.DateTime s4Future07Field;
        
        private System.DateTime s4Future08Field;
        
        private int s4Future09Field;
        
        private int s4Future10Field;
        
        private string s4Future11Field;
        
        private string s4Future12Field;
        
        private string salutField;
        
        private string stateField;
        
        private string typeField;
        
        private string user1Field;
        
        private System.DateTime user10Field;
        
        private string user2Field;
        
        private string user3Field;
        
        private string user4Field;
        
        private double user5Field;
        
        private double user6Field;
        
        private string user7Field;
        
        private string user8Field;
        
        private System.DateTime user9Field;
        
        private string webSiteField;
        
        private string zipField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Addr1 {
            get {
                return this.addr1Field;
            }
            set {
                this.addr1Field = value;
            }
        }
        
        /// <remarks/>
        public string Addr2 {
            get {
                return this.addr2Field;
            }
            set {
                this.addr2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactID {
            get {
                return this.contactIDField;
            }
            set {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Crtd_DateTime {
            get {
                return this.crtd_DateTimeField;
            }
            set {
                this.crtd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_Prog {
            get {
                return this.crtd_ProgField;
            }
            set {
                this.crtd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_User {
            get {
                return this.crtd_UserField;
            }
            set {
                this.crtd_UserField = value;
            }
        }
        
        /// <remarks/>
        public string CustID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddr {
            get {
                return this.emailAddrField;
            }
            set {
                this.emailAddrField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LUpd_DateTime {
            get {
                return this.lUpd_DateTimeField;
            }
            set {
                this.lUpd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_Prog {
            get {
                return this.lUpd_ProgField;
            }
            set {
                this.lUpd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_User {
            get {
                return this.lUpd_UserField;
            }
            set {
                this.lUpd_UserField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int NoteID {
            get {
                return this.noteIDField;
            }
            set {
                this.noteIDField = value;
            }
        }
        
        /// <remarks/>
        public double OrderLimit {
            get {
                return this.orderLimitField;
            }
            set {
                this.orderLimitField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public double POReqdAmt {
            get {
                return this.pOReqdAmtField;
            }
            set {
                this.pOReqdAmtField = value;
            }
        }
        
        /// <remarks/>
        public string S4Future01 {
            get {
                return this.s4Future01Field;
            }
            set {
                this.s4Future01Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future02 {
            get {
                return this.s4Future02Field;
            }
            set {
                this.s4Future02Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future03 {
            get {
                return this.s4Future03Field;
            }
            set {
                this.s4Future03Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future04 {
            get {
                return this.s4Future04Field;
            }
            set {
                this.s4Future04Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future05 {
            get {
                return this.s4Future05Field;
            }
            set {
                this.s4Future05Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future06 {
            get {
                return this.s4Future06Field;
            }
            set {
                this.s4Future06Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future07 {
            get {
                return this.s4Future07Field;
            }
            set {
                this.s4Future07Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future08 {
            get {
                return this.s4Future08Field;
            }
            set {
                this.s4Future08Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future09 {
            get {
                return this.s4Future09Field;
            }
            set {
                this.s4Future09Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future10 {
            get {
                return this.s4Future10Field;
            }
            set {
                this.s4Future10Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future11 {
            get {
                return this.s4Future11Field;
            }
            set {
                this.s4Future11Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future12 {
            get {
                return this.s4Future12Field;
            }
            set {
                this.s4Future12Field = value;
            }
        }
        
        /// <remarks/>
        public string Salut {
            get {
                return this.salutField;
            }
            set {
                this.salutField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string User1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User10 {
            get {
                return this.user10Field;
            }
            set {
                this.user10Field = value;
            }
        }
        
        /// <remarks/>
        public string User2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public string User3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public string User4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public double User5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public double User6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public string User7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public string User8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User9 {
            get {
                return this.user9Field;
            }
            set {
                this.user9Field = value;
            }
        }
        
        /// <remarks/>
        public string WebSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class genericReturn {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void aboutCompletedEventHandler(object sender, aboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsByCustIDCompletedEventHandler(object sender, getCustContactsByCustIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustContactsByCustIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustContactsByCustIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsByIDCompletedEventHandler(object sender, getCustContactsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustContactsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustContactsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactByExactIDCompletedEventHandler(object sender, getCustContactByExactIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustContactByExactIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustContactByExactIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void validateCustIDCompletedEventHandler(object sender, validateCustIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateCustIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateCustIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public genericReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((genericReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getScreenByCustIDCompletedEventHandler(object sender, getScreenByCustIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScreenByCustIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScreenByCustIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNewscreenCompletedEventHandler(object sender, getNewscreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewscreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewscreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editScreenCompletedEventHandler(object sender, editScreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editNoteCompletedEventHandler(object sender, editNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Snote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Snote)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editNoteAsDataSetCompletedEventHandler(object sender, editNoteAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editNoteAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editNoteAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editCustContactCompletedEventHandler(object sender, editCustContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editCustContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editCustContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editCustContactAsJSONCompletedEventHandler(object sender, editCustContactAsJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editCustContactAsJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editCustContactAsJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editCustContactAsDataSetCompletedEventHandler(object sender, editCustContactAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editCustContactAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editCustContactAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editCustContactAsDataSetAsJSONCompletedEventHandler(object sender, editCustContactAsDataSetAsJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editCustContactAsDataSetAsJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editCustContactAsDataSetAsJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNewCustContactCompletedEventHandler(object sender, getNewCustContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewCustContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewCustContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNewCustContactAsJSONCompletedEventHandler(object sender, getNewCustContactAsJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewCustContactAsJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewCustContactAsJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsCompletedEventHandler(object sender, getCustContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustContact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustContact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsAsJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsAsDataSetCompletedEventHandler(object sender, getCustContactsAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustContactsAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustContactsAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCustContactsAsDataSetAsJSONCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void pingCompletedEventHandler(object sender, pingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591