//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace client.ctDynamicsSL.quickQuery.ctDynamicsSL.quickQuery {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="quickQuerySoap", Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class quickQuery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback aboutOperationCompleted;
        
        private ctDynamicsSLHeader ctDynamicsSLHeaderValueField;
        
        private System.Threading.SendOrPostCallback getScreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQueryViewsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQueryViewsByExactIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback pingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public quickQuery() {
            this.Url = global::client.ctDynamicsSL.quickQuery.Properties.Settings.Default.client_ctDynamicsSL_quickQuery_ctDynamicsSL_quickQuery_quickQuery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ctDynamicsSLHeader ctDynamicsSLHeaderValue {
            get {
                return this.ctDynamicsSLHeaderValueField;
            }
            set {
                this.ctDynamicsSLHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event aboutCompletedEventHandler aboutCompleted;
        
        /// <remarks/>
        public event getScreenCompletedEventHandler getScreenCompleted;
        
        /// <remarks/>
        public event getQueryViewsByIDCompletedEventHandler getQueryViewsByIDCompleted;
        
        /// <remarks/>
        public event getQueryViewsByExactIDCompletedEventHandler getQueryViewsByExactIDCompleted;
        
        /// <remarks/>
        public event pingCompletedEventHandler pingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/about", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string about() {
            object[] results = this.Invoke("about", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aboutAsync() {
            this.aboutAsync(null);
        }
        
        /// <remarks/>
        public void aboutAsync(object userState) {
            if ((this.aboutOperationCompleted == null)) {
                this.aboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaboutOperationCompleted);
            }
            this.InvokeAsync("about", new object[0], this.aboutOperationCompleted, userState);
        }
        
        private void OnaboutOperationCompleted(object arg) {
            if ((this.aboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aboutCompleted(this, new aboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getScreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen getScreen(string queryViewName, queryFilter[] filters) {
            object[] results = this.Invoke("getScreen", new object[] {
                        queryViewName,
                        filters});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void getScreenAsync(string queryViewName, queryFilter[] filters) {
            this.getScreenAsync(queryViewName, filters, null);
        }
        
        /// <remarks/>
        public void getScreenAsync(string queryViewName, queryFilter[] filters, object userState) {
            if ((this.getScreenOperationCompleted == null)) {
                this.getScreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScreenOperationCompleted);
            }
            this.InvokeAsync("getScreen", new object[] {
                        queryViewName,
                        filters}, this.getScreenOperationCompleted, userState);
        }
        
        private void OngetScreenOperationCompleted(object arg) {
            if ((this.getScreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScreenCompleted(this, new getScreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getQueryViewsByID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vs_qvcatalog[] getQueryViewsByID(string queryViewName) {
            object[] results = this.Invoke("getQueryViewsByID", new object[] {
                        queryViewName});
            return ((vs_qvcatalog[])(results[0]));
        }
        
        /// <remarks/>
        public void getQueryViewsByIDAsync(string queryViewName) {
            this.getQueryViewsByIDAsync(queryViewName, null);
        }
        
        /// <remarks/>
        public void getQueryViewsByIDAsync(string queryViewName, object userState) {
            if ((this.getQueryViewsByIDOperationCompleted == null)) {
                this.getQueryViewsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQueryViewsByIDOperationCompleted);
            }
            this.InvokeAsync("getQueryViewsByID", new object[] {
                        queryViewName}, this.getQueryViewsByIDOperationCompleted, userState);
        }
        
        private void OngetQueryViewsByIDOperationCompleted(object arg) {
            if ((this.getQueryViewsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQueryViewsByIDCompleted(this, new getQueryViewsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getQueryViewsByExactID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public vs_qvcatalog getQueryViewsByExactID(string queryViewName) {
            object[] results = this.Invoke("getQueryViewsByExactID", new object[] {
                        queryViewName});
            return ((vs_qvcatalog)(results[0]));
        }
        
        /// <remarks/>
        public void getQueryViewsByExactIDAsync(string queryViewName) {
            this.getQueryViewsByExactIDAsync(queryViewName, null);
        }
        
        /// <remarks/>
        public void getQueryViewsByExactIDAsync(string queryViewName, object userState) {
            if ((this.getQueryViewsByExactIDOperationCompleted == null)) {
                this.getQueryViewsByExactIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQueryViewsByExactIDOperationCompleted);
            }
            this.InvokeAsync("getQueryViewsByExactID", new object[] {
                        queryViewName}, this.getQueryViewsByExactIDOperationCompleted, userState);
        }
        
        private void OngetQueryViewsByExactIDOperationCompleted(object arg) {
            if ((this.getQueryViewsByExactIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQueryViewsByExactIDCompleted(this, new getQueryViewsByExactIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/ping", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ping(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            object[] results = this.Invoke("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            this.pingAsync(pingType, siteID, siteKey, licenseKey, licenseName, licenseExpiration, softwareName, null);
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName, object userState) {
            if ((this.pingOperationCompleted == null)) {
                this.pingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpingOperationCompleted);
            }
            this.InvokeAsync("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName}, this.pingOperationCompleted, userState);
        }
        
        private void OnpingOperationCompleted(object arg) {
            if ((this.pingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pingCompleted(this, new pingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL", IsNullable=false)]
    public partial class ctDynamicsSLHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string licenseKeyField;
        
        private string licenseNameField;
        
        private string licenseExpirationField;
        
        private string softwareNameField;
        
        private string siteIDField;
        
        private string siteKeyField;
        
        private string userNameField;
        
        private string cpnyIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string licenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        public string licenseName {
            get {
                return this.licenseNameField;
            }
            set {
                this.licenseNameField = value;
            }
        }
        
        /// <remarks/>
        public string licenseExpiration {
            get {
                return this.licenseExpirationField;
            }
            set {
                this.licenseExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string softwareName {
            get {
                return this.softwareNameField;
            }
            set {
                this.softwareNameField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteKey {
            get {
                return this.siteKeyField;
            }
            set {
                this.siteKeyField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string cpnyID {
            get {
                return this.cpnyIDField;
            }
            set {
                this.cpnyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class vs_qvcatalog {
        
        private string errorMessageField;
        
        private int resultCodeField;
        
        private string sQLViewField;
        
        private string baseQueryViewField;
        
        private string queryViewNameField;
        
        private string moduleField;
        
        private string numberField;
        
        private string viewDescriptionField;
        
        private string viewFilterField;
        
        private string viewSortField;
        
        private string columnsRemovedMovedField;
        
        private string drillProgramsField;
        
        private short visibilityTypeField;
        
        private string visibilityField;
        
        private short systemDatabaseField;
        
        private string companyColumnField;
        
        private short companyParmsField;
        
        private string noteColumnsField;
        
        private string createdByField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SQLView {
            get {
                return this.sQLViewField;
            }
            set {
                this.sQLViewField = value;
            }
        }
        
        /// <remarks/>
        public string BaseQueryView {
            get {
                return this.baseQueryViewField;
            }
            set {
                this.baseQueryViewField = value;
            }
        }
        
        /// <remarks/>
        public string QueryViewName {
            get {
                return this.queryViewNameField;
            }
            set {
                this.queryViewNameField = value;
            }
        }
        
        /// <remarks/>
        public string Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string ViewDescription {
            get {
                return this.viewDescriptionField;
            }
            set {
                this.viewDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ViewFilter {
            get {
                return this.viewFilterField;
            }
            set {
                this.viewFilterField = value;
            }
        }
        
        /// <remarks/>
        public string ViewSort {
            get {
                return this.viewSortField;
            }
            set {
                this.viewSortField = value;
            }
        }
        
        /// <remarks/>
        public string ColumnsRemovedMoved {
            get {
                return this.columnsRemovedMovedField;
            }
            set {
                this.columnsRemovedMovedField = value;
            }
        }
        
        /// <remarks/>
        public string DrillPrograms {
            get {
                return this.drillProgramsField;
            }
            set {
                this.drillProgramsField = value;
            }
        }
        
        /// <remarks/>
        public short VisibilityType {
            get {
                return this.visibilityTypeField;
            }
            set {
                this.visibilityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public short SystemDatabase {
            get {
                return this.systemDatabaseField;
            }
            set {
                this.systemDatabaseField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyColumn {
            get {
                return this.companyColumnField;
            }
            set {
                this.companyColumnField = value;
            }
        }
        
        /// <remarks/>
        public short CompanyParms {
            get {
                return this.companyParmsField;
            }
            set {
                this.companyParmsField = value;
            }
        }
        
        /// <remarks/>
        public string NoteColumns {
            get {
                return this.noteColumnsField;
            }
            set {
                this.noteColumnsField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class screen {
        
        private vs_qvcatalog myQueryViewField;
        
        private System.Data.DataSet myQueryResultsField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public vs_qvcatalog myQueryView {
            get {
                return this.myQueryViewField;
            }
            set {
                this.myQueryViewField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet myQueryResults {
            get {
                return this.myQueryResultsField;
            }
            set {
                this.myQueryResultsField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class queryFilter {
        
        private string nameField;
        
        private string valueField;
        
        private string comparisonTypeField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string comparisonType {
            get {
                return this.comparisonTypeField;
            }
            set {
                this.comparisonTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void aboutCompletedEventHandler(object sender, aboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getScreenCompletedEventHandler(object sender, getScreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getQueryViewsByIDCompletedEventHandler(object sender, getQueryViewsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQueryViewsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQueryViewsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vs_qvcatalog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vs_qvcatalog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getQueryViewsByExactIDCompletedEventHandler(object sender, getQueryViewsByExactIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQueryViewsByExactIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQueryViewsByExactIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vs_qvcatalog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vs_qvcatalog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void pingCompletedEventHandler(object sender, pingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591