//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace client.ctQueue.ctDynamicsSL.queue {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="queueSoap", Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class queue : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback aboutOperationCompleted;
        
        private ctDynamicsSLHeader ctDynamicsSLHeaderValueField;
        
        private System.Threading.SendOrPostCallback editDSLXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback editDSLXMLAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewDSLXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLsAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLByExactIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback editDSLXMLLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback editDSLXMLLogAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewDSLXMLLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLLogsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLLogsAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLStatisticsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSLXMLStatisticsAsDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback copyDSLXMLToLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback pingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public queue() {
            this.Url = global::client.ctQueue.Properties.Settings.Default.client_ctQueue_ctDynamicsSL_queue_queue;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ctDynamicsSLHeader ctDynamicsSLHeaderValue {
            get {
                return this.ctDynamicsSLHeaderValueField;
            }
            set {
                this.ctDynamicsSLHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event aboutCompletedEventHandler aboutCompleted;
        
        /// <remarks/>
        public event editDSLXMLCompletedEventHandler editDSLXMLCompleted;
        
        /// <remarks/>
        public event editDSLXMLAsDataSetCompletedEventHandler editDSLXMLAsDataSetCompleted;
        
        /// <remarks/>
        public event getNewDSLXMLCompletedEventHandler getNewDSLXMLCompleted;
        
        /// <remarks/>
        public event getDSLXMLsCompletedEventHandler getDSLXMLsCompleted;
        
        /// <remarks/>
        public event getDSLXMLsAsDataSetCompletedEventHandler getDSLXMLsAsDataSetCompleted;
        
        /// <remarks/>
        public event getDSLXMLsByIDCompletedEventHandler getDSLXMLsByIDCompleted;
        
        /// <remarks/>
        public event getDSLXMLByExactIDCompletedEventHandler getDSLXMLByExactIDCompleted;
        
        /// <remarks/>
        public event editDSLXMLLogCompletedEventHandler editDSLXMLLogCompleted;
        
        /// <remarks/>
        public event editDSLXMLLogAsDataSetCompletedEventHandler editDSLXMLLogAsDataSetCompleted;
        
        /// <remarks/>
        public event getNewDSLXMLLogCompletedEventHandler getNewDSLXMLLogCompleted;
        
        /// <remarks/>
        public event getDSLXMLLogsCompletedEventHandler getDSLXMLLogsCompleted;
        
        /// <remarks/>
        public event getDSLXMLLogsAsDataSetCompletedEventHandler getDSLXMLLogsAsDataSetCompleted;
        
        /// <remarks/>
        public event getDSLXMLStatisticsCompletedEventHandler getDSLXMLStatisticsCompleted;
        
        /// <remarks/>
        public event getDSLXMLStatisticsAsDataSetCompletedEventHandler getDSLXMLStatisticsAsDataSetCompleted;
        
        /// <remarks/>
        public event copyDSLXMLToLogCompletedEventHandler copyDSLXMLToLogCompleted;
        
        /// <remarks/>
        public event pingCompletedEventHandler pingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/about", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string about() {
            object[] results = this.Invoke("about", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aboutAsync() {
            this.aboutAsync(null);
        }
        
        /// <remarks/>
        public void aboutAsync(object userState) {
            if ((this.aboutOperationCompleted == null)) {
                this.aboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaboutOperationCompleted);
            }
            this.InvokeAsync("about", new object[0], this.aboutOperationCompleted, userState);
        }
        
        private void OnaboutOperationCompleted(object arg) {
            if ((this.aboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aboutCompleted(this, new aboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editDSLXML", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXML editDSLXML(string actionType, DSLXML inItem) {
            object[] results = this.Invoke("editDSLXML", new object[] {
                        actionType,
                        inItem});
            return ((DSLXML)(results[0]));
        }
        
        /// <remarks/>
        public void editDSLXMLAsync(string actionType, DSLXML inItem) {
            this.editDSLXMLAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editDSLXMLAsync(string actionType, DSLXML inItem, object userState) {
            if ((this.editDSLXMLOperationCompleted == null)) {
                this.editDSLXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditDSLXMLOperationCompleted);
            }
            this.InvokeAsync("editDSLXML", new object[] {
                        actionType,
                        inItem}, this.editDSLXMLOperationCompleted, userState);
        }
        
        private void OneditDSLXMLOperationCompleted(object arg) {
            if ((this.editDSLXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editDSLXMLCompleted(this, new editDSLXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editDSLXMLAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet editDSLXMLAsDataSet(string actionType, DSLXML inItem) {
            object[] results = this.Invoke("editDSLXMLAsDataSet", new object[] {
                        actionType,
                        inItem});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void editDSLXMLAsDataSetAsync(string actionType, DSLXML inItem) {
            this.editDSLXMLAsDataSetAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editDSLXMLAsDataSetAsync(string actionType, DSLXML inItem, object userState) {
            if ((this.editDSLXMLAsDataSetOperationCompleted == null)) {
                this.editDSLXMLAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditDSLXMLAsDataSetOperationCompleted);
            }
            this.InvokeAsync("editDSLXMLAsDataSet", new object[] {
                        actionType,
                        inItem}, this.editDSLXMLAsDataSetOperationCompleted, userState);
        }
        
        private void OneditDSLXMLAsDataSetOperationCompleted(object arg) {
            if ((this.editDSLXMLAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editDSLXMLAsDataSetCompleted(this, new editDSLXMLAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewDSLXML", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXML getNewDSLXML(DSLXML inTemplate) {
            object[] results = this.Invoke("getNewDSLXML", new object[] {
                        inTemplate});
            return ((DSLXML)(results[0]));
        }
        
        /// <remarks/>
        public void getNewDSLXMLAsync(DSLXML inTemplate) {
            this.getNewDSLXMLAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewDSLXMLAsync(DSLXML inTemplate, object userState) {
            if ((this.getNewDSLXMLOperationCompleted == null)) {
                this.getNewDSLXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewDSLXMLOperationCompleted);
            }
            this.InvokeAsync("getNewDSLXML", new object[] {
                        inTemplate}, this.getNewDSLXMLOperationCompleted, userState);
        }
        
        private void OngetNewDSLXMLOperationCompleted(object arg) {
            if ((this.getNewDSLXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewDSLXMLCompleted(this, new getNewDSLXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLs", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXML[] getDSLXMLs(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLs", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((DSLXML[])(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLsAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLsOperationCompleted == null)) {
                this.getDSLXMLsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLsOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLs", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLsOperationCompleted, userState);
        }
        
        private void OngetDSLXMLsOperationCompleted(object arg) {
            if ((this.getDSLXMLsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLsCompleted(this, new getDSLXMLsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLsAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDSLXMLsAsDataSet(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLsAsDataSetAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLsAsDataSetOperationCompleted == null)) {
                this.getDSLXMLsAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLsAsDataSetOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLsAsDataSetOperationCompleted, userState);
        }
        
        private void OngetDSLXMLsAsDataSetOperationCompleted(object arg) {
            if ((this.getDSLXMLsAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLsAsDataSetCompleted(this, new getDSLXMLsAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLsByID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXML[] getDSLXMLsByID(string xmlGUID) {
            object[] results = this.Invoke("getDSLXMLsByID", new object[] {
                        xmlGUID});
            return ((DSLXML[])(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLsByIDAsync(string xmlGUID) {
            this.getDSLXMLsByIDAsync(xmlGUID, null);
        }
        
        /// <remarks/>
        public void getDSLXMLsByIDAsync(string xmlGUID, object userState) {
            if ((this.getDSLXMLsByIDOperationCompleted == null)) {
                this.getDSLXMLsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLsByIDOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLsByID", new object[] {
                        xmlGUID}, this.getDSLXMLsByIDOperationCompleted, userState);
        }
        
        private void OngetDSLXMLsByIDOperationCompleted(object arg) {
            if ((this.getDSLXMLsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLsByIDCompleted(this, new getDSLXMLsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLByExactID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXML getDSLXMLByExactID(string xmlGUID) {
            object[] results = this.Invoke("getDSLXMLByExactID", new object[] {
                        xmlGUID});
            return ((DSLXML)(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLByExactIDAsync(string xmlGUID) {
            this.getDSLXMLByExactIDAsync(xmlGUID, null);
        }
        
        /// <remarks/>
        public void getDSLXMLByExactIDAsync(string xmlGUID, object userState) {
            if ((this.getDSLXMLByExactIDOperationCompleted == null)) {
                this.getDSLXMLByExactIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLByExactIDOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLByExactID", new object[] {
                        xmlGUID}, this.getDSLXMLByExactIDOperationCompleted, userState);
        }
        
        private void OngetDSLXMLByExactIDOperationCompleted(object arg) {
            if ((this.getDSLXMLByExactIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLByExactIDCompleted(this, new getDSLXMLByExactIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editDSLXMLLog", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXMLLog editDSLXMLLog(string actionType, DSLXMLLog inItem) {
            object[] results = this.Invoke("editDSLXMLLog", new object[] {
                        actionType,
                        inItem});
            return ((DSLXMLLog)(results[0]));
        }
        
        /// <remarks/>
        public void editDSLXMLLogAsync(string actionType, DSLXMLLog inItem) {
            this.editDSLXMLLogAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editDSLXMLLogAsync(string actionType, DSLXMLLog inItem, object userState) {
            if ((this.editDSLXMLLogOperationCompleted == null)) {
                this.editDSLXMLLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditDSLXMLLogOperationCompleted);
            }
            this.InvokeAsync("editDSLXMLLog", new object[] {
                        actionType,
                        inItem}, this.editDSLXMLLogOperationCompleted, userState);
        }
        
        private void OneditDSLXMLLogOperationCompleted(object arg) {
            if ((this.editDSLXMLLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editDSLXMLLogCompleted(this, new editDSLXMLLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editDSLXMLLogAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet editDSLXMLLogAsDataSet(string actionType, DSLXMLLog inItem) {
            object[] results = this.Invoke("editDSLXMLLogAsDataSet", new object[] {
                        actionType,
                        inItem});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void editDSLXMLLogAsDataSetAsync(string actionType, DSLXMLLog inItem) {
            this.editDSLXMLLogAsDataSetAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editDSLXMLLogAsDataSetAsync(string actionType, DSLXMLLog inItem, object userState) {
            if ((this.editDSLXMLLogAsDataSetOperationCompleted == null)) {
                this.editDSLXMLLogAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditDSLXMLLogAsDataSetOperationCompleted);
            }
            this.InvokeAsync("editDSLXMLLogAsDataSet", new object[] {
                        actionType,
                        inItem}, this.editDSLXMLLogAsDataSetOperationCompleted, userState);
        }
        
        private void OneditDSLXMLLogAsDataSetOperationCompleted(object arg) {
            if ((this.editDSLXMLLogAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editDSLXMLLogAsDataSetCompleted(this, new editDSLXMLLogAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewDSLXMLLog", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXMLLog getNewDSLXMLLog(DSLXMLLog inTemplate) {
            object[] results = this.Invoke("getNewDSLXMLLog", new object[] {
                        inTemplate});
            return ((DSLXMLLog)(results[0]));
        }
        
        /// <remarks/>
        public void getNewDSLXMLLogAsync(DSLXMLLog inTemplate) {
            this.getNewDSLXMLLogAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewDSLXMLLogAsync(DSLXMLLog inTemplate, object userState) {
            if ((this.getNewDSLXMLLogOperationCompleted == null)) {
                this.getNewDSLXMLLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewDSLXMLLogOperationCompleted);
            }
            this.InvokeAsync("getNewDSLXMLLog", new object[] {
                        inTemplate}, this.getNewDSLXMLLogOperationCompleted, userState);
        }
        
        private void OngetNewDSLXMLLogOperationCompleted(object arg) {
            if ((this.getNewDSLXMLLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewDSLXMLLogCompleted(this, new getNewDSLXMLLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLLogs", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXMLLog[] getDSLXMLLogs(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLLogs", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((DSLXMLLog[])(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLLogsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLLogsAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLLogsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLLogsOperationCompleted == null)) {
                this.getDSLXMLLogsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLLogsOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLLogs", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLLogsOperationCompleted, userState);
        }
        
        private void OngetDSLXMLLogsOperationCompleted(object arg) {
            if ((this.getDSLXMLLogsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLLogsCompleted(this, new getDSLXMLLogsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLLogsAsDataSet", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDSLXMLLogsAsDataSet(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLLogsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLLogsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLLogsAsDataSetAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLLogsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLLogsAsDataSetOperationCompleted == null)) {
                this.getDSLXMLLogsAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLLogsAsDataSetOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLLogsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLLogsAsDataSetOperationCompleted, userState);
        }
        
        private void OngetDSLXMLLogsAsDataSetOperationCompleted(object arg) {
            if ((this.getDSLXMLLogsAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLLogsAsDataSetCompleted(this, new getDSLXMLLogsAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLStatistics", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public genericResultPair[] getDSLXMLStatistics(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLStatistics", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((genericResultPair[])(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLStatisticsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLStatisticsAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLStatisticsAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLStatisticsOperationCompleted == null)) {
                this.getDSLXMLStatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLStatisticsOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLStatistics", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLStatisticsOperationCompleted, userState);
        }
        
        private void OngetDSLXMLStatisticsOperationCompleted(object arg) {
            if ((this.getDSLXMLStatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLStatisticsCompleted(this, new getDSLXMLStatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getDSLXMLStatisticsAsData" +
            "Set", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getDSLXMLStatisticsAsDataSet(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            object[] results = this.Invoke("getDSLXMLStatisticsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getDSLXMLStatisticsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms) {
            this.getDSLXMLStatisticsAsDataSetAsync(currentPageNumber, pageSize, parms, null);
        }
        
        /// <remarks/>
        public void getDSLXMLStatisticsAsDataSetAsync(int currentPageNumber, int pageSize, nameValuePairs[] parms, object userState) {
            if ((this.getDSLXMLStatisticsAsDataSetOperationCompleted == null)) {
                this.getDSLXMLStatisticsAsDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSLXMLStatisticsAsDataSetOperationCompleted);
            }
            this.InvokeAsync("getDSLXMLStatisticsAsDataSet", new object[] {
                        currentPageNumber,
                        pageSize,
                        parms}, this.getDSLXMLStatisticsAsDataSetOperationCompleted, userState);
        }
        
        private void OngetDSLXMLStatisticsAsDataSetOperationCompleted(object arg) {
            if ((this.getDSLXMLStatisticsAsDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSLXMLStatisticsAsDataSetCompleted(this, new getDSLXMLStatisticsAsDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/copyDSLXMLToLog", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DSLXMLLog copyDSLXMLToLog(string xmlGUID, string logNote, bool deleteSource) {
            object[] results = this.Invoke("copyDSLXMLToLog", new object[] {
                        xmlGUID,
                        logNote,
                        deleteSource});
            return ((DSLXMLLog)(results[0]));
        }
        
        /// <remarks/>
        public void copyDSLXMLToLogAsync(string xmlGUID, string logNote, bool deleteSource) {
            this.copyDSLXMLToLogAsync(xmlGUID, logNote, deleteSource, null);
        }
        
        /// <remarks/>
        public void copyDSLXMLToLogAsync(string xmlGUID, string logNote, bool deleteSource, object userState) {
            if ((this.copyDSLXMLToLogOperationCompleted == null)) {
                this.copyDSLXMLToLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OncopyDSLXMLToLogOperationCompleted);
            }
            this.InvokeAsync("copyDSLXMLToLog", new object[] {
                        xmlGUID,
                        logNote,
                        deleteSource}, this.copyDSLXMLToLogOperationCompleted, userState);
        }
        
        private void OncopyDSLXMLToLogOperationCompleted(object arg) {
            if ((this.copyDSLXMLToLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.copyDSLXMLToLogCompleted(this, new copyDSLXMLToLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/ping", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ping(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            object[] results = this.Invoke("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            this.pingAsync(pingType, siteID, siteKey, licenseKey, licenseName, licenseExpiration, softwareName, null);
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName, object userState) {
            if ((this.pingOperationCompleted == null)) {
                this.pingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpingOperationCompleted);
            }
            this.InvokeAsync("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName}, this.pingOperationCompleted, userState);
        }
        
        private void OnpingOperationCompleted(object arg) {
            if ((this.pingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pingCompleted(this, new pingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL", IsNullable=false)]
    public partial class ctDynamicsSLHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string licenseKeyField;
        
        private string licenseNameField;
        
        private string licenseExpirationField;
        
        private string softwareNameField;
        
        private string siteIDField;
        
        private string siteKeyField;
        
        private string userNameField;
        
        private string cpnyIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string licenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        public string licenseName {
            get {
                return this.licenseNameField;
            }
            set {
                this.licenseNameField = value;
            }
        }
        
        /// <remarks/>
        public string licenseExpiration {
            get {
                return this.licenseExpirationField;
            }
            set {
                this.licenseExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string softwareName {
            get {
                return this.softwareNameField;
            }
            set {
                this.softwareNameField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteKey {
            get {
                return this.siteKeyField;
            }
            set {
                this.siteKeyField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string cpnyID {
            get {
                return this.cpnyIDField;
            }
            set {
                this.cpnyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class genericResultPair {
        
        private string errorMessageField;
        
        private int resultCodeField;
        
        private string nameField;
        
        private string valueField;
        
        private int sortIndexField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        private string user5Field;
        
        private string user6Field;
        
        private System.DateTime user7Field;
        
        private System.DateTime user8Field;
        
        private short user9Field;
        
        private short user10Field;
        
        private string user11Field;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int sortIndex {
            get {
                return this.sortIndexField;
            }
            set {
                this.sortIndexField = value;
            }
        }
        
        /// <remarks/>
        public string user1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string user2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double user3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double user4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public string user5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public string user6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public short user9 {
            get {
                return this.user9Field;
            }
            set {
                this.user9Field = value;
            }
        }
        
        /// <remarks/>
        public short user10 {
            get {
                return this.user10Field;
            }
            set {
                this.user10Field = value;
            }
        }
        
        /// <remarks/>
        public string user11 {
            get {
                return this.user11Field;
            }
            set {
                this.user11Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class DSLXMLLog {
        
        private string errorMessageField;
        
        private string notesField;
        
        private int resultCodeField;
        
        private string logGUIDField;
        
        private System.DateTime logDateField;
        
        private string logNoteField;
        
        private string xmlGUIDField;
        
        private string siteIDField;
        
        private string itemIDField;
        
        private string itemTypeField;
        
        private string statusField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastUpdatedField;
        
        private string xmlContentField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        private string user5Field;
        
        private string user6Field;
        
        private System.DateTime user7Field;
        
        private System.DateTime user8Field;
        
        private short user9Field;
        
        private short user10Field;
        
        private string user11Field;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string logGUID {
            get {
                return this.logGUIDField;
            }
            set {
                this.logGUIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime logDate {
            get {
                return this.logDateField;
            }
            set {
                this.logDateField = value;
            }
        }
        
        /// <remarks/>
        public string logNote {
            get {
                return this.logNoteField;
            }
            set {
                this.logNoteField = value;
            }
        }
        
        /// <remarks/>
        public string xmlGUID {
            get {
                return this.xmlGUIDField;
            }
            set {
                this.xmlGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string itemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public string itemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public string xmlContent {
            get {
                return this.xmlContentField;
            }
            set {
                this.xmlContentField = value;
            }
        }
        
        /// <remarks/>
        public string user1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string user2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double user3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double user4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public string user5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public string user6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public short user9 {
            get {
                return this.user9Field;
            }
            set {
                this.user9Field = value;
            }
        }
        
        /// <remarks/>
        public short user10 {
            get {
                return this.user10Field;
            }
            set {
                this.user10Field = value;
            }
        }
        
        /// <remarks/>
        public string user11 {
            get {
                return this.user11Field;
            }
            set {
                this.user11Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class nameValuePairs {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class DSLXML {
        
        private string errorMessageField;
        
        private int resultCodeField;
        
        private string xmlGUIDField;
        
        private string siteIDField;
        
        private string itemIDField;
        
        private string itemTypeField;
        
        private string statusField;
        
        private System.DateTime createdDateField;
        
        private System.DateTime lastUpdatedField;
        
        private string xmlContentField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        private string user5Field;
        
        private string user6Field;
        
        private System.DateTime user7Field;
        
        private System.DateTime user8Field;
        
        private short user9Field;
        
        private short user10Field;
        
        private string user11Field;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string xmlGUID {
            get {
                return this.xmlGUIDField;
            }
            set {
                this.xmlGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string itemID {
            get {
                return this.itemIDField;
            }
            set {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        public string itemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public string xmlContent {
            get {
                return this.xmlContentField;
            }
            set {
                this.xmlContentField = value;
            }
        }
        
        /// <remarks/>
        public string user1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string user2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double user3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double user4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public string user5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public string user6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime user8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public short user9 {
            get {
                return this.user9Field;
            }
            set {
                this.user9Field = value;
            }
        }
        
        /// <remarks/>
        public short user10 {
            get {
                return this.user10Field;
            }
            set {
                this.user10Field = value;
            }
        }
        
        /// <remarks/>
        public string user11 {
            get {
                return this.user11Field;
            }
            set {
                this.user11Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void aboutCompletedEventHandler(object sender, aboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editDSLXMLCompletedEventHandler(object sender, editDSLXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editDSLXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editDSLXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXML Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXML)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editDSLXMLAsDataSetCompletedEventHandler(object sender, editDSLXMLAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editDSLXMLAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editDSLXMLAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNewDSLXMLCompletedEventHandler(object sender, getNewDSLXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewDSLXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewDSLXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXML Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXML)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLsCompletedEventHandler(object sender, getDSLXMLsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXML[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXML[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLsAsDataSetCompletedEventHandler(object sender, getDSLXMLsAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLsAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLsAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLsByIDCompletedEventHandler(object sender, getDSLXMLsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXML[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXML[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLByExactIDCompletedEventHandler(object sender, getDSLXMLByExactIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLByExactIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLByExactIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXML Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXML)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editDSLXMLLogCompletedEventHandler(object sender, editDSLXMLLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editDSLXMLLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editDSLXMLLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXMLLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXMLLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void editDSLXMLLogAsDataSetCompletedEventHandler(object sender, editDSLXMLLogAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editDSLXMLLogAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editDSLXMLLogAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getNewDSLXMLLogCompletedEventHandler(object sender, getNewDSLXMLLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewDSLXMLLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewDSLXMLLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXMLLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXMLLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLLogsCompletedEventHandler(object sender, getDSLXMLLogsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXMLLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXMLLog[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLLogsAsDataSetCompletedEventHandler(object sender, getDSLXMLLogsAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLLogsAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLLogsAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLStatisticsCompletedEventHandler(object sender, getDSLXMLStatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLStatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLStatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public genericResultPair[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((genericResultPair[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDSLXMLStatisticsAsDataSetCompletedEventHandler(object sender, getDSLXMLStatisticsAsDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSLXMLStatisticsAsDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSLXMLStatisticsAsDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void copyDSLXMLToLogCompletedEventHandler(object sender, copyDSLXMLToLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class copyDSLXMLToLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal copyDSLXMLToLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DSLXMLLog Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DSLXMLLog)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void pingCompletedEventHandler(object sender, pingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591