//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.orderManagement.maintenance.customerContacts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/customerContacts.asmx")]
        public string client_orderManagement_maintenance_customerContacts_ctDynamicsSL_orderManagement_maintenance_customerContacts_customerContacts {
            get {
                return ((string)(this["client_orderManagement_maintenance_customerContacts_ctDynamicsSL_orderManagement_" +
                    "maintenance_customerContacts_customerContacts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/customerMaintenance.asmx")]
        public string client_orderManagement_maintenance_customerContacts_ctDynamicsSL_financial_accountsReceivable_maintenance_customerMaintenance_customerMaintenance {
            get {
                return ((string)(this["client_orderManagement_maintenance_customerContacts_ctDynamicsSL_financial_accoun" +
                    "tsReceivable_maintenance_customerMaintenance_customerMaintenance"]));
            }
        }
    }
}
