//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace client.project.timeAndExpense.maintenance.projectExpenseTypeMaintenance.ctDynamicsSL.project.timeAndExpense.maintenance.projectExpenseTypeMaintenance {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="projectExpenseTypeMaintenanceSoap", Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class projectExpenseTypeMaintenance : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback aboutOperationCompleted;
        
        private ctDynamicsSLHeader ctDynamicsSLHeaderValueField;
        
        private System.Threading.SendOrPostCallback editScreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback editPJEXPTYPOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewscreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNewPJEXPTYPOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPJEXPTYPByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPJEXPTYPByExactIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAccountsByAcctOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTaxIDsByTaxIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback pingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public projectExpenseTypeMaintenance() {
            this.Url = global::client.project.timeAndExpense.maintenance.projectExpenseTypeMaintenance.Properties.Settings.Default.client_project_timeAndExpense_maintenance_projectExpenseTypeMaintenance_ctDynamicsSL_project_timeAndExpense_maintenance_projectExpenseTypeMaintenance_projectExpenseTypeMaintenance;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ctDynamicsSLHeader ctDynamicsSLHeaderValue {
            get {
                return this.ctDynamicsSLHeaderValueField;
            }
            set {
                this.ctDynamicsSLHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event aboutCompletedEventHandler aboutCompleted;
        
        /// <remarks/>
        public event editScreenCompletedEventHandler editScreenCompleted;
        
        /// <remarks/>
        public event editPJEXPTYPCompletedEventHandler editPJEXPTYPCompleted;
        
        /// <remarks/>
        public event getNewscreenCompletedEventHandler getNewscreenCompleted;
        
        /// <remarks/>
        public event getNewPJEXPTYPCompletedEventHandler getNewPJEXPTYPCompleted;
        
        /// <remarks/>
        public event getScreenCompletedEventHandler getScreenCompleted;
        
        /// <remarks/>
        public event getPJEXPTYPByIDCompletedEventHandler getPJEXPTYPByIDCompleted;
        
        /// <remarks/>
        public event getPJEXPTYPByExactIDCompletedEventHandler getPJEXPTYPByExactIDCompleted;
        
        /// <remarks/>
        public event getAccountsByAcctCompletedEventHandler getAccountsByAcctCompleted;
        
        /// <remarks/>
        public event getTaxIDsByTaxIDCompletedEventHandler getTaxIDsByTaxIDCompleted;
        
        /// <remarks/>
        public event pingCompletedEventHandler pingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/about", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string about() {
            object[] results = this.Invoke("about", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aboutAsync() {
            this.aboutAsync(null);
        }
        
        /// <remarks/>
        public void aboutAsync(object userState) {
            if ((this.aboutOperationCompleted == null)) {
                this.aboutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaboutOperationCompleted);
            }
            this.InvokeAsync("about", new object[0], this.aboutOperationCompleted, userState);
        }
        
        private void OnaboutOperationCompleted(object arg) {
            if ((this.aboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aboutCompleted(this, new aboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editScreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen editScreen(string actionType, screen inScreen) {
            object[] results = this.Invoke("editScreen", new object[] {
                        actionType,
                        inScreen});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void editScreenAsync(string actionType, screen inScreen) {
            this.editScreenAsync(actionType, inScreen, null);
        }
        
        /// <remarks/>
        public void editScreenAsync(string actionType, screen inScreen, object userState) {
            if ((this.editScreenOperationCompleted == null)) {
                this.editScreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditScreenOperationCompleted);
            }
            this.InvokeAsync("editScreen", new object[] {
                        actionType,
                        inScreen}, this.editScreenOperationCompleted, userState);
        }
        
        private void OneditScreenOperationCompleted(object arg) {
            if ((this.editScreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editScreenCompleted(this, new editScreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/editPJEXPTYP", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PJEXPTYP editPJEXPTYP(string actionType, PJEXPTYP inItem) {
            object[] results = this.Invoke("editPJEXPTYP", new object[] {
                        actionType,
                        inItem});
            return ((PJEXPTYP)(results[0]));
        }
        
        /// <remarks/>
        public void editPJEXPTYPAsync(string actionType, PJEXPTYP inItem) {
            this.editPJEXPTYPAsync(actionType, inItem, null);
        }
        
        /// <remarks/>
        public void editPJEXPTYPAsync(string actionType, PJEXPTYP inItem, object userState) {
            if ((this.editPJEXPTYPOperationCompleted == null)) {
                this.editPJEXPTYPOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditPJEXPTYPOperationCompleted);
            }
            this.InvokeAsync("editPJEXPTYP", new object[] {
                        actionType,
                        inItem}, this.editPJEXPTYPOperationCompleted, userState);
        }
        
        private void OneditPJEXPTYPOperationCompleted(object arg) {
            if ((this.editPJEXPTYPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editPJEXPTYPCompleted(this, new editPJEXPTYPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewscreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen getNewscreen(screen inTemplate) {
            object[] results = this.Invoke("getNewscreen", new object[] {
                        inTemplate});
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void getNewscreenAsync(screen inTemplate) {
            this.getNewscreenAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewscreenAsync(screen inTemplate, object userState) {
            if ((this.getNewscreenOperationCompleted == null)) {
                this.getNewscreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewscreenOperationCompleted);
            }
            this.InvokeAsync("getNewscreen", new object[] {
                        inTemplate}, this.getNewscreenOperationCompleted, userState);
        }
        
        private void OngetNewscreenOperationCompleted(object arg) {
            if ((this.getNewscreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewscreenCompleted(this, new getNewscreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getNewPJEXPTYP", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PJEXPTYP getNewPJEXPTYP(PJEXPTYP inTemplate) {
            object[] results = this.Invoke("getNewPJEXPTYP", new object[] {
                        inTemplate});
            return ((PJEXPTYP)(results[0]));
        }
        
        /// <remarks/>
        public void getNewPJEXPTYPAsync(PJEXPTYP inTemplate) {
            this.getNewPJEXPTYPAsync(inTemplate, null);
        }
        
        /// <remarks/>
        public void getNewPJEXPTYPAsync(PJEXPTYP inTemplate, object userState) {
            if ((this.getNewPJEXPTYPOperationCompleted == null)) {
                this.getNewPJEXPTYPOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewPJEXPTYPOperationCompleted);
            }
            this.InvokeAsync("getNewPJEXPTYP", new object[] {
                        inTemplate}, this.getNewPJEXPTYPOperationCompleted, userState);
        }
        
        private void OngetNewPJEXPTYPOperationCompleted(object arg) {
            if ((this.getNewPJEXPTYPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewPJEXPTYPCompleted(this, new getNewPJEXPTYPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getScreen", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public screen getScreen() {
            object[] results = this.Invoke("getScreen", new object[0]);
            return ((screen)(results[0]));
        }
        
        /// <remarks/>
        public void getScreenAsync() {
            this.getScreenAsync(null);
        }
        
        /// <remarks/>
        public void getScreenAsync(object userState) {
            if ((this.getScreenOperationCompleted == null)) {
                this.getScreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScreenOperationCompleted);
            }
            this.InvokeAsync("getScreen", new object[0], this.getScreenOperationCompleted, userState);
        }
        
        private void OngetScreenOperationCompleted(object arg) {
            if ((this.getScreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScreenCompleted(this, new getScreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getPJEXPTYPByID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PJEXPTYP[] getPJEXPTYPByID(string exp_type) {
            object[] results = this.Invoke("getPJEXPTYPByID", new object[] {
                        exp_type});
            return ((PJEXPTYP[])(results[0]));
        }
        
        /// <remarks/>
        public void getPJEXPTYPByIDAsync(string exp_type) {
            this.getPJEXPTYPByIDAsync(exp_type, null);
        }
        
        /// <remarks/>
        public void getPJEXPTYPByIDAsync(string exp_type, object userState) {
            if ((this.getPJEXPTYPByIDOperationCompleted == null)) {
                this.getPJEXPTYPByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPJEXPTYPByIDOperationCompleted);
            }
            this.InvokeAsync("getPJEXPTYPByID", new object[] {
                        exp_type}, this.getPJEXPTYPByIDOperationCompleted, userState);
        }
        
        private void OngetPJEXPTYPByIDOperationCompleted(object arg) {
            if ((this.getPJEXPTYPByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPJEXPTYPByIDCompleted(this, new getPJEXPTYPByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getPJEXPTYPByExactID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PJEXPTYP getPJEXPTYPByExactID(string exp_type) {
            object[] results = this.Invoke("getPJEXPTYPByExactID", new object[] {
                        exp_type});
            return ((PJEXPTYP)(results[0]));
        }
        
        /// <remarks/>
        public void getPJEXPTYPByExactIDAsync(string exp_type) {
            this.getPJEXPTYPByExactIDAsync(exp_type, null);
        }
        
        /// <remarks/>
        public void getPJEXPTYPByExactIDAsync(string exp_type, object userState) {
            if ((this.getPJEXPTYPByExactIDOperationCompleted == null)) {
                this.getPJEXPTYPByExactIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPJEXPTYPByExactIDOperationCompleted);
            }
            this.InvokeAsync("getPJEXPTYPByExactID", new object[] {
                        exp_type}, this.getPJEXPTYPByExactIDOperationCompleted, userState);
        }
        
        private void OngetPJEXPTYPByExactIDOperationCompleted(object arg) {
            if ((this.getPJEXPTYPByExactIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPJEXPTYPByExactIDCompleted(this, new getPJEXPTYPByExactIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getAccountsByAcct", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Account[] getAccountsByAcct(string acct) {
            object[] results = this.Invoke("getAccountsByAcct", new object[] {
                        acct});
            return ((Account[])(results[0]));
        }
        
        /// <remarks/>
        public void getAccountsByAcctAsync(string acct) {
            this.getAccountsByAcctAsync(acct, null);
        }
        
        /// <remarks/>
        public void getAccountsByAcctAsync(string acct, object userState) {
            if ((this.getAccountsByAcctOperationCompleted == null)) {
                this.getAccountsByAcctOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAccountsByAcctOperationCompleted);
            }
            this.InvokeAsync("getAccountsByAcct", new object[] {
                        acct}, this.getAccountsByAcctOperationCompleted, userState);
        }
        
        private void OngetAccountsByAcctOperationCompleted(object arg) {
            if ((this.getAccountsByAcctCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAccountsByAcctCompleted(this, new getAccountsByAcctCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ctDynamicsSLHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/getTaxIDsByTaxID", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalesTax[] getTaxIDsByTaxID(string taxID) {
            object[] results = this.Invoke("getTaxIDsByTaxID", new object[] {
                        taxID});
            return ((SalesTax[])(results[0]));
        }
        
        /// <remarks/>
        public void getTaxIDsByTaxIDAsync(string taxID) {
            this.getTaxIDsByTaxIDAsync(taxID, null);
        }
        
        /// <remarks/>
        public void getTaxIDsByTaxIDAsync(string taxID, object userState) {
            if ((this.getTaxIDsByTaxIDOperationCompleted == null)) {
                this.getTaxIDsByTaxIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTaxIDsByTaxIDOperationCompleted);
            }
            this.InvokeAsync("getTaxIDsByTaxID", new object[] {
                        taxID}, this.getTaxIDsByTaxIDOperationCompleted, userState);
        }
        
        private void OngetTaxIDsByTaxIDOperationCompleted(object arg) {
            if ((this.getTaxIDsByTaxIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTaxIDsByTaxIDCompleted(this, new getTaxIDsByTaxIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.catalinatechnology.com/services/ctDynamicsSL/ping", RequestNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", ResponseNamespace="http://www.catalinatechnology.com/services/ctDynamicsSL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ping(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            object[] results = this.Invoke("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName) {
            this.pingAsync(pingType, siteID, siteKey, licenseKey, licenseName, licenseExpiration, softwareName, null);
        }
        
        /// <remarks/>
        public void pingAsync(string pingType, string siteID, string siteKey, string licenseKey, string licenseName, string licenseExpiration, string softwareName, object userState) {
            if ((this.pingOperationCompleted == null)) {
                this.pingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpingOperationCompleted);
            }
            this.InvokeAsync("ping", new object[] {
                        pingType,
                        siteID,
                        siteKey,
                        licenseKey,
                        licenseName,
                        licenseExpiration,
                        softwareName}, this.pingOperationCompleted, userState);
        }
        
        private void OnpingOperationCompleted(object arg) {
            if ((this.pingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pingCompleted(this, new pingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL", IsNullable=false)]
    public partial class ctDynamicsSLHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string licenseKeyField;
        
        private string licenseNameField;
        
        private string licenseExpirationField;
        
        private string softwareNameField;
        
        private string siteIDField;
        
        private string siteKeyField;
        
        private string userNameField;
        
        private string cpnyIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string licenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        public string licenseName {
            get {
                return this.licenseNameField;
            }
            set {
                this.licenseNameField = value;
            }
        }
        
        /// <remarks/>
        public string licenseExpiration {
            get {
                return this.licenseExpirationField;
            }
            set {
                this.licenseExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string softwareName {
            get {
                return this.softwareNameField;
            }
            set {
                this.softwareNameField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string siteKey {
            get {
                return this.siteKeyField;
            }
            set {
                this.siteKeyField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string cpnyID {
            get {
                return this.cpnyIDField;
            }
            set {
                this.cpnyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class SalesTax {
        
        private string errorMessageField;
        
        private string notesField;
        
        private int resultCodeField;
        
        private string accruTaxAcctField;
        
        private string accruTaxesubAcctField;
        
        private string adjByTermsDiscField;
        
        private string applTermDiscField;
        
        private short applTermsDiscTaxField;
        
        private string aPTaxPtDateField;
        
        private string aRTaxPtDateField;
        
        private string catExcept00Field;
        
        private string catExcept01Field;
        
        private string catExcept02Field;
        
        private string catExcept03Field;
        
        private string catExcept04Field;
        
        private string catExcept05Field;
        
        private string catFlgField;
        
        private System.DateTime crtd_DateTimeField;
        
        private string crtd_ProgField;
        
        private string crtd_UserField;
        
        private string descrField;
        
        private string exemptionField;
        
        private string exemTaxIdField;
        
        private short exp_to_Proj_SwField;
        
        private string expTaxAcctField;
        
        private string expTaxesubField;
        
        private string filingLocField;
        
        private short groupDetCntField;
        
        private string groupIDField;
        
        private string groupRuleField;
        
        private string inclFrtField;
        
        private string inclInDocTotField;
        
        private string inclmiscField;
        
        private string liabTaxAcctField;
        
        private string liabTaxesubField;
        
        private string localCodeField;
        
        private string longIdField;
        
        private System.DateTime lUpd_DateTimeField;
        
        private string lUpd_ProgField;
        
        private string lUpd_UserField;
        
        private short lvl2ExmptField;
        
        private System.DateTime newRateDateField;
        
        private double newTaxRateField;
        
        private int noteIdField;
        
        private double oldTaxRateField;
        
        private string oPTaxPtDateField;
        
        private string pOTaxPtDateField;
        
        private string prcTaxInclField;
        
        private string purTaxAcctField;
        
        private string purTaxDiscAcctField;
        
        private string purTaxDiscSubField;
        
        private string purTaxesubField;
        
        private double rateAboveMaxField;
        
        private string s4Future01Field;
        
        private string s4Future02Field;
        
        private double s4Future03Field;
        
        private double s4Future04Field;
        
        private double s4Future05Field;
        
        private double s4Future06Field;
        
        private System.DateTime s4Future07Field;
        
        private System.DateTime s4Future08Field;
        
        private int s4Future09Field;
        
        private int s4Future10Field;
        
        private string s4Future11Field;
        
        private string s4Future12Field;
        
        private string slsTaxAcctField;
        
        private string slsTaxDiscAcctField;
        
        private string slsTaxDiscSubField;
        
        private string slsTaxesubField;
        
        private string taxAuthLvlField;
        
        private string taxBasisField;
        
        private string taxCalcLvlField;
        
        private string taxCalcMethField;
        
        private string taxCalcTypeField;
        
        private string taxIdField;
        
        private double taxRateField;
        
        private System.DateTime taxRvsdDateField;
        
        private string taxTypeField;
        
        private double txblAdjPctField;
        
        private double txblMaxField;
        
        private double txblMinField;
        
        private string txblMinMaxCuryIDField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        private string user5Field;
        
        private string user6Field;
        
        private System.DateTime user7Field;
        
        private System.DateTime user8Field;
        
        private string vendIDField;
        
        private short voucherTaxField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccruTaxAcct {
            get {
                return this.accruTaxAcctField;
            }
            set {
                this.accruTaxAcctField = value;
            }
        }
        
        /// <remarks/>
        public string AccruTaxesubAcct {
            get {
                return this.accruTaxesubAcctField;
            }
            set {
                this.accruTaxesubAcctField = value;
            }
        }
        
        /// <remarks/>
        public string AdjByTermsDisc {
            get {
                return this.adjByTermsDiscField;
            }
            set {
                this.adjByTermsDiscField = value;
            }
        }
        
        /// <remarks/>
        public string ApplTermDisc {
            get {
                return this.applTermDiscField;
            }
            set {
                this.applTermDiscField = value;
            }
        }
        
        /// <remarks/>
        public short ApplTermsDiscTax {
            get {
                return this.applTermsDiscTaxField;
            }
            set {
                this.applTermsDiscTaxField = value;
            }
        }
        
        /// <remarks/>
        public string APTaxPtDate {
            get {
                return this.aPTaxPtDateField;
            }
            set {
                this.aPTaxPtDateField = value;
            }
        }
        
        /// <remarks/>
        public string ARTaxPtDate {
            get {
                return this.aRTaxPtDateField;
            }
            set {
                this.aRTaxPtDateField = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept00 {
            get {
                return this.catExcept00Field;
            }
            set {
                this.catExcept00Field = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept01 {
            get {
                return this.catExcept01Field;
            }
            set {
                this.catExcept01Field = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept02 {
            get {
                return this.catExcept02Field;
            }
            set {
                this.catExcept02Field = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept03 {
            get {
                return this.catExcept03Field;
            }
            set {
                this.catExcept03Field = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept04 {
            get {
                return this.catExcept04Field;
            }
            set {
                this.catExcept04Field = value;
            }
        }
        
        /// <remarks/>
        public string CatExcept05 {
            get {
                return this.catExcept05Field;
            }
            set {
                this.catExcept05Field = value;
            }
        }
        
        /// <remarks/>
        public string CatFlg {
            get {
                return this.catFlgField;
            }
            set {
                this.catFlgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Crtd_DateTime {
            get {
                return this.crtd_DateTimeField;
            }
            set {
                this.crtd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_Prog {
            get {
                return this.crtd_ProgField;
            }
            set {
                this.crtd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_User {
            get {
                return this.crtd_UserField;
            }
            set {
                this.crtd_UserField = value;
            }
        }
        
        /// <remarks/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <remarks/>
        public string Exemption {
            get {
                return this.exemptionField;
            }
            set {
                this.exemptionField = value;
            }
        }
        
        /// <remarks/>
        public string ExemTaxId {
            get {
                return this.exemTaxIdField;
            }
            set {
                this.exemTaxIdField = value;
            }
        }
        
        /// <remarks/>
        public short Exp_to_Proj_Sw {
            get {
                return this.exp_to_Proj_SwField;
            }
            set {
                this.exp_to_Proj_SwField = value;
            }
        }
        
        /// <remarks/>
        public string ExpTaxAcct {
            get {
                return this.expTaxAcctField;
            }
            set {
                this.expTaxAcctField = value;
            }
        }
        
        /// <remarks/>
        public string ExpTaxesub {
            get {
                return this.expTaxesubField;
            }
            set {
                this.expTaxesubField = value;
            }
        }
        
        /// <remarks/>
        public string FilingLoc {
            get {
                return this.filingLocField;
            }
            set {
                this.filingLocField = value;
            }
        }
        
        /// <remarks/>
        public short GroupDetCnt {
            get {
                return this.groupDetCntField;
            }
            set {
                this.groupDetCntField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupRule {
            get {
                return this.groupRuleField;
            }
            set {
                this.groupRuleField = value;
            }
        }
        
        /// <remarks/>
        public string InclFrt {
            get {
                return this.inclFrtField;
            }
            set {
                this.inclFrtField = value;
            }
        }
        
        /// <remarks/>
        public string InclInDocTot {
            get {
                return this.inclInDocTotField;
            }
            set {
                this.inclInDocTotField = value;
            }
        }
        
        /// <remarks/>
        public string Inclmisc {
            get {
                return this.inclmiscField;
            }
            set {
                this.inclmiscField = value;
            }
        }
        
        /// <remarks/>
        public string LiabTaxAcct {
            get {
                return this.liabTaxAcctField;
            }
            set {
                this.liabTaxAcctField = value;
            }
        }
        
        /// <remarks/>
        public string LiabTaxesub {
            get {
                return this.liabTaxesubField;
            }
            set {
                this.liabTaxesubField = value;
            }
        }
        
        /// <remarks/>
        public string LocalCode {
            get {
                return this.localCodeField;
            }
            set {
                this.localCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LongId {
            get {
                return this.longIdField;
            }
            set {
                this.longIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LUpd_DateTime {
            get {
                return this.lUpd_DateTimeField;
            }
            set {
                this.lUpd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_Prog {
            get {
                return this.lUpd_ProgField;
            }
            set {
                this.lUpd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_User {
            get {
                return this.lUpd_UserField;
            }
            set {
                this.lUpd_UserField = value;
            }
        }
        
        /// <remarks/>
        public short Lvl2Exmpt {
            get {
                return this.lvl2ExmptField;
            }
            set {
                this.lvl2ExmptField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NewRateDate {
            get {
                return this.newRateDateField;
            }
            set {
                this.newRateDateField = value;
            }
        }
        
        /// <remarks/>
        public double NewTaxRate {
            get {
                return this.newTaxRateField;
            }
            set {
                this.newTaxRateField = value;
            }
        }
        
        /// <remarks/>
        public int NoteId {
            get {
                return this.noteIdField;
            }
            set {
                this.noteIdField = value;
            }
        }
        
        /// <remarks/>
        public double OldTaxRate {
            get {
                return this.oldTaxRateField;
            }
            set {
                this.oldTaxRateField = value;
            }
        }
        
        /// <remarks/>
        public string OPTaxPtDate {
            get {
                return this.oPTaxPtDateField;
            }
            set {
                this.oPTaxPtDateField = value;
            }
        }
        
        /// <remarks/>
        public string POTaxPtDate {
            get {
                return this.pOTaxPtDateField;
            }
            set {
                this.pOTaxPtDateField = value;
            }
        }
        
        /// <remarks/>
        public string PrcTaxIncl {
            get {
                return this.prcTaxInclField;
            }
            set {
                this.prcTaxInclField = value;
            }
        }
        
        /// <remarks/>
        public string PurTaxAcct {
            get {
                return this.purTaxAcctField;
            }
            set {
                this.purTaxAcctField = value;
            }
        }
        
        /// <remarks/>
        public string PurTaxDiscAcct {
            get {
                return this.purTaxDiscAcctField;
            }
            set {
                this.purTaxDiscAcctField = value;
            }
        }
        
        /// <remarks/>
        public string PurTaxDiscSub {
            get {
                return this.purTaxDiscSubField;
            }
            set {
                this.purTaxDiscSubField = value;
            }
        }
        
        /// <remarks/>
        public string PurTaxesub {
            get {
                return this.purTaxesubField;
            }
            set {
                this.purTaxesubField = value;
            }
        }
        
        /// <remarks/>
        public double RateAboveMax {
            get {
                return this.rateAboveMaxField;
            }
            set {
                this.rateAboveMaxField = value;
            }
        }
        
        /// <remarks/>
        public string S4Future01 {
            get {
                return this.s4Future01Field;
            }
            set {
                this.s4Future01Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future02 {
            get {
                return this.s4Future02Field;
            }
            set {
                this.s4Future02Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future03 {
            get {
                return this.s4Future03Field;
            }
            set {
                this.s4Future03Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future04 {
            get {
                return this.s4Future04Field;
            }
            set {
                this.s4Future04Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future05 {
            get {
                return this.s4Future05Field;
            }
            set {
                this.s4Future05Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future06 {
            get {
                return this.s4Future06Field;
            }
            set {
                this.s4Future06Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future07 {
            get {
                return this.s4Future07Field;
            }
            set {
                this.s4Future07Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future08 {
            get {
                return this.s4Future08Field;
            }
            set {
                this.s4Future08Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future09 {
            get {
                return this.s4Future09Field;
            }
            set {
                this.s4Future09Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future10 {
            get {
                return this.s4Future10Field;
            }
            set {
                this.s4Future10Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future11 {
            get {
                return this.s4Future11Field;
            }
            set {
                this.s4Future11Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future12 {
            get {
                return this.s4Future12Field;
            }
            set {
                this.s4Future12Field = value;
            }
        }
        
        /// <remarks/>
        public string SlsTaxAcct {
            get {
                return this.slsTaxAcctField;
            }
            set {
                this.slsTaxAcctField = value;
            }
        }
        
        /// <remarks/>
        public string SlsTaxDiscAcct {
            get {
                return this.slsTaxDiscAcctField;
            }
            set {
                this.slsTaxDiscAcctField = value;
            }
        }
        
        /// <remarks/>
        public string SlsTaxDiscSub {
            get {
                return this.slsTaxDiscSubField;
            }
            set {
                this.slsTaxDiscSubField = value;
            }
        }
        
        /// <remarks/>
        public string SlsTaxesub {
            get {
                return this.slsTaxesubField;
            }
            set {
                this.slsTaxesubField = value;
            }
        }
        
        /// <remarks/>
        public string TaxAuthLvl {
            get {
                return this.taxAuthLvlField;
            }
            set {
                this.taxAuthLvlField = value;
            }
        }
        
        /// <remarks/>
        public string TaxBasis {
            get {
                return this.taxBasisField;
            }
            set {
                this.taxBasisField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCalcLvl {
            get {
                return this.taxCalcLvlField;
            }
            set {
                this.taxCalcLvlField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCalcMeth {
            get {
                return this.taxCalcMethField;
            }
            set {
                this.taxCalcMethField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCalcType {
            get {
                return this.taxCalcTypeField;
            }
            set {
                this.taxCalcTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TaxId {
            get {
                return this.taxIdField;
            }
            set {
                this.taxIdField = value;
            }
        }
        
        /// <remarks/>
        public double TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TaxRvsdDate {
            get {
                return this.taxRvsdDateField;
            }
            set {
                this.taxRvsdDateField = value;
            }
        }
        
        /// <remarks/>
        public string TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        public double TxblAdjPct {
            get {
                return this.txblAdjPctField;
            }
            set {
                this.txblAdjPctField = value;
            }
        }
        
        /// <remarks/>
        public double TxblMax {
            get {
                return this.txblMaxField;
            }
            set {
                this.txblMaxField = value;
            }
        }
        
        /// <remarks/>
        public double TxblMin {
            get {
                return this.txblMinField;
            }
            set {
                this.txblMinField = value;
            }
        }
        
        /// <remarks/>
        public string TxblMinMaxCuryID {
            get {
                return this.txblMinMaxCuryIDField;
            }
            set {
                this.txblMinMaxCuryIDField = value;
            }
        }
        
        /// <remarks/>
        public string User1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string User2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double User3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double User4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public string User5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public string User6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public string VendID {
            get {
                return this.vendIDField;
            }
            set {
                this.vendIDField = value;
            }
        }
        
        /// <remarks/>
        public short VoucherTax {
            get {
                return this.voucherTaxField;
            }
            set {
                this.voucherTaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class Account {
        
        private string errorMessageField;
        
        private int resultCodeField;
        
        private string acctField;
        
        private string acctTypeField;
        
        private string acct_CatField;
        
        private string acct_Cat_SWField;
        
        private short activeField;
        
        private string classIDField;
        
        private string consolAcctField;
        
        private System.DateTime crtd_DateTimeField;
        
        private string crtd_ProgField;
        
        private string crtd_UserField;
        
        private string curyIdField;
        
        private string descrField;
        
        private string employ_SwField;
        
        private System.DateTime lUpd_DateTimeField;
        
        private string lUpd_ProgField;
        
        private string lUpd_UserField;
        
        private int noteIDField;
        
        private string ratioGrpField;
        
        private string s4Future01Field;
        
        private string s4Future02Field;
        
        private double s4Future03Field;
        
        private double s4Future04Field;
        
        private double s4Future05Field;
        
        private double s4Future06Field;
        
        private System.DateTime s4Future07Field;
        
        private System.DateTime s4Future08Field;
        
        private int s4Future09Field;
        
        private int s4Future10Field;
        
        private string s4Future11Field;
        
        private string s4Future12Field;
        
        private string summPostField;
        
        private string unitofMeasField;
        
        private string units_SWField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        private string user5Field;
        
        private string user6Field;
        
        private System.DateTime user7Field;
        
        private System.DateTime user8Field;
        
        private string validateIDField;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Acct {
            get {
                return this.acctField;
            }
            set {
                this.acctField = value;
            }
        }
        
        /// <remarks/>
        public string AcctType {
            get {
                return this.acctTypeField;
            }
            set {
                this.acctTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Acct_Cat {
            get {
                return this.acct_CatField;
            }
            set {
                this.acct_CatField = value;
            }
        }
        
        /// <remarks/>
        public string Acct_Cat_SW {
            get {
                return this.acct_Cat_SWField;
            }
            set {
                this.acct_Cat_SWField = value;
            }
        }
        
        /// <remarks/>
        public short Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string ConsolAcct {
            get {
                return this.consolAcctField;
            }
            set {
                this.consolAcctField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Crtd_DateTime {
            get {
                return this.crtd_DateTimeField;
            }
            set {
                this.crtd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_Prog {
            get {
                return this.crtd_ProgField;
            }
            set {
                this.crtd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string Crtd_User {
            get {
                return this.crtd_UserField;
            }
            set {
                this.crtd_UserField = value;
            }
        }
        
        /// <remarks/>
        public string CuryId {
            get {
                return this.curyIdField;
            }
            set {
                this.curyIdField = value;
            }
        }
        
        /// <remarks/>
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
            }
        }
        
        /// <remarks/>
        public string Employ_Sw {
            get {
                return this.employ_SwField;
            }
            set {
                this.employ_SwField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LUpd_DateTime {
            get {
                return this.lUpd_DateTimeField;
            }
            set {
                this.lUpd_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_Prog {
            get {
                return this.lUpd_ProgField;
            }
            set {
                this.lUpd_ProgField = value;
            }
        }
        
        /// <remarks/>
        public string LUpd_User {
            get {
                return this.lUpd_UserField;
            }
            set {
                this.lUpd_UserField = value;
            }
        }
        
        /// <remarks/>
        public int NoteID {
            get {
                return this.noteIDField;
            }
            set {
                this.noteIDField = value;
            }
        }
        
        /// <remarks/>
        public string RatioGrp {
            get {
                return this.ratioGrpField;
            }
            set {
                this.ratioGrpField = value;
            }
        }
        
        /// <remarks/>
        public string S4Future01 {
            get {
                return this.s4Future01Field;
            }
            set {
                this.s4Future01Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future02 {
            get {
                return this.s4Future02Field;
            }
            set {
                this.s4Future02Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future03 {
            get {
                return this.s4Future03Field;
            }
            set {
                this.s4Future03Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future04 {
            get {
                return this.s4Future04Field;
            }
            set {
                this.s4Future04Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future05 {
            get {
                return this.s4Future05Field;
            }
            set {
                this.s4Future05Field = value;
            }
        }
        
        /// <remarks/>
        public double S4Future06 {
            get {
                return this.s4Future06Field;
            }
            set {
                this.s4Future06Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future07 {
            get {
                return this.s4Future07Field;
            }
            set {
                this.s4Future07Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime S4Future08 {
            get {
                return this.s4Future08Field;
            }
            set {
                this.s4Future08Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future09 {
            get {
                return this.s4Future09Field;
            }
            set {
                this.s4Future09Field = value;
            }
        }
        
        /// <remarks/>
        public int S4Future10 {
            get {
                return this.s4Future10Field;
            }
            set {
                this.s4Future10Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future11 {
            get {
                return this.s4Future11Field;
            }
            set {
                this.s4Future11Field = value;
            }
        }
        
        /// <remarks/>
        public string S4Future12 {
            get {
                return this.s4Future12Field;
            }
            set {
                this.s4Future12Field = value;
            }
        }
        
        /// <remarks/>
        public string SummPost {
            get {
                return this.summPostField;
            }
            set {
                this.summPostField = value;
            }
        }
        
        /// <remarks/>
        public string UnitofMeas {
            get {
                return this.unitofMeasField;
            }
            set {
                this.unitofMeasField = value;
            }
        }
        
        /// <remarks/>
        public string Units_SW {
            get {
                return this.units_SWField;
            }
            set {
                this.units_SWField = value;
            }
        }
        
        /// <remarks/>
        public string User1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string User2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double User3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double User4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
        
        /// <remarks/>
        public string User5 {
            get {
                return this.user5Field;
            }
            set {
                this.user5Field = value;
            }
        }
        
        /// <remarks/>
        public string User6 {
            get {
                return this.user6Field;
            }
            set {
                this.user6Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User7 {
            get {
                return this.user7Field;
            }
            set {
                this.user7Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime User8 {
            get {
                return this.user8Field;
            }
            set {
                this.user8Field = value;
            }
        }
        
        /// <remarks/>
        public string ValidateID {
            get {
                return this.validateIDField;
            }
            set {
                this.validateIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class PJEXPTYP {
        
        private string errorMessageField;
        
        private string notesField;
        
        private int resultCodeField;
        
        private System.DateTime crtd_datetimeField;
        
        private string crtd_progField;
        
        private string crtd_userField;
        
        private double default_rateField;
        
        private string desc_expField;
        
        private string ex_id01Field;
        
        private string ex_id02Field;
        
        private string ex_id03Field;
        
        private string ex_id04Field;
        
        private string ex_id05Field;
        
        private double ex_id06Field;
        
        private double ex_id07Field;
        
        private System.DateTime ex_id08Field;
        
        private System.DateTime ex_id09Field;
        
        private int ex_id10Field;
        
        private string exp_typeField;
        
        private string gl_acctField;
        
        private System.DateTime lupd_datetimeField;
        
        private string lupd_progField;
        
        private string lupd_userField;
        
        private int noteIdField;
        
        private string statusField;
        
        private string tax_flagField;
        
        private string taxidField;
        
        private string units_flagField;
        
        private string user1Field;
        
        private string user2Field;
        
        private double user3Field;
        
        private double user4Field;
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime crtd_datetime {
            get {
                return this.crtd_datetimeField;
            }
            set {
                this.crtd_datetimeField = value;
            }
        }
        
        /// <remarks/>
        public string crtd_prog {
            get {
                return this.crtd_progField;
            }
            set {
                this.crtd_progField = value;
            }
        }
        
        /// <remarks/>
        public string crtd_user {
            get {
                return this.crtd_userField;
            }
            set {
                this.crtd_userField = value;
            }
        }
        
        /// <remarks/>
        public double default_rate {
            get {
                return this.default_rateField;
            }
            set {
                this.default_rateField = value;
            }
        }
        
        /// <remarks/>
        public string desc_exp {
            get {
                return this.desc_expField;
            }
            set {
                this.desc_expField = value;
            }
        }
        
        /// <remarks/>
        public string ex_id01 {
            get {
                return this.ex_id01Field;
            }
            set {
                this.ex_id01Field = value;
            }
        }
        
        /// <remarks/>
        public string ex_id02 {
            get {
                return this.ex_id02Field;
            }
            set {
                this.ex_id02Field = value;
            }
        }
        
        /// <remarks/>
        public string ex_id03 {
            get {
                return this.ex_id03Field;
            }
            set {
                this.ex_id03Field = value;
            }
        }
        
        /// <remarks/>
        public string ex_id04 {
            get {
                return this.ex_id04Field;
            }
            set {
                this.ex_id04Field = value;
            }
        }
        
        /// <remarks/>
        public string ex_id05 {
            get {
                return this.ex_id05Field;
            }
            set {
                this.ex_id05Field = value;
            }
        }
        
        /// <remarks/>
        public double ex_id06 {
            get {
                return this.ex_id06Field;
            }
            set {
                this.ex_id06Field = value;
            }
        }
        
        /// <remarks/>
        public double ex_id07 {
            get {
                return this.ex_id07Field;
            }
            set {
                this.ex_id07Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ex_id08 {
            get {
                return this.ex_id08Field;
            }
            set {
                this.ex_id08Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ex_id09 {
            get {
                return this.ex_id09Field;
            }
            set {
                this.ex_id09Field = value;
            }
        }
        
        /// <remarks/>
        public int ex_id10 {
            get {
                return this.ex_id10Field;
            }
            set {
                this.ex_id10Field = value;
            }
        }
        
        /// <remarks/>
        public string exp_type {
            get {
                return this.exp_typeField;
            }
            set {
                this.exp_typeField = value;
            }
        }
        
        /// <remarks/>
        public string gl_acct {
            get {
                return this.gl_acctField;
            }
            set {
                this.gl_acctField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lupd_datetime {
            get {
                return this.lupd_datetimeField;
            }
            set {
                this.lupd_datetimeField = value;
            }
        }
        
        /// <remarks/>
        public string lupd_prog {
            get {
                return this.lupd_progField;
            }
            set {
                this.lupd_progField = value;
            }
        }
        
        /// <remarks/>
        public string lupd_user {
            get {
                return this.lupd_userField;
            }
            set {
                this.lupd_userField = value;
            }
        }
        
        /// <remarks/>
        public int NoteId {
            get {
                return this.noteIdField;
            }
            set {
                this.noteIdField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string tax_flag {
            get {
                return this.tax_flagField;
            }
            set {
                this.tax_flagField = value;
            }
        }
        
        /// <remarks/>
        public string taxid {
            get {
                return this.taxidField;
            }
            set {
                this.taxidField = value;
            }
        }
        
        /// <remarks/>
        public string units_flag {
            get {
                return this.units_flagField;
            }
            set {
                this.units_flagField = value;
            }
        }
        
        /// <remarks/>
        public string user1 {
            get {
                return this.user1Field;
            }
            set {
                this.user1Field = value;
            }
        }
        
        /// <remarks/>
        public string user2 {
            get {
                return this.user2Field;
            }
            set {
                this.user2Field = value;
            }
        }
        
        /// <remarks/>
        public double user3 {
            get {
                return this.user3Field;
            }
            set {
                this.user3Field = value;
            }
        }
        
        /// <remarks/>
        public double user4 {
            get {
                return this.user4Field;
            }
            set {
                this.user4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.catalinatechnology.com/services/ctDynamicsSL")]
    public partial class screen {
        
        private PJEXPTYP[] myPJEXPTYPField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public PJEXPTYP[] myPJEXPTYP {
            get {
                return this.myPJEXPTYPField;
            }
            set {
                this.myPJEXPTYPField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void aboutCompletedEventHandler(object sender, aboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void editScreenCompletedEventHandler(object sender, editScreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void editPJEXPTYPCompletedEventHandler(object sender, editPJEXPTYPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editPJEXPTYPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal editPJEXPTYPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PJEXPTYP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PJEXPTYP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getNewscreenCompletedEventHandler(object sender, getNewscreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewscreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewscreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getNewPJEXPTYPCompletedEventHandler(object sender, getNewPJEXPTYPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewPJEXPTYPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNewPJEXPTYPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PJEXPTYP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PJEXPTYP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getScreenCompletedEventHandler(object sender, getScreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public screen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((screen)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getPJEXPTYPByIDCompletedEventHandler(object sender, getPJEXPTYPByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPJEXPTYPByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPJEXPTYPByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PJEXPTYP[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PJEXPTYP[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getPJEXPTYPByExactIDCompletedEventHandler(object sender, getPJEXPTYPByExactIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPJEXPTYPByExactIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPJEXPTYPByExactIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PJEXPTYP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PJEXPTYP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getAccountsByAcctCompletedEventHandler(object sender, getAccountsByAcctCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAccountsByAcctCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAccountsByAcctCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Account[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Account[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getTaxIDsByTaxIDCompletedEventHandler(object sender, getTaxIDsByTaxIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTaxIDsByTaxIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTaxIDsByTaxIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesTax[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesTax[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void pingCompletedEventHandler(object sender, pingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591