//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.project.timeAndExpense.input.projectTimecardWithRateAmtEntry.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/projectTimecardWithRateAmtEntry.asmx" +
            "")]
        public string client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_projectTimecardWithRateAmtEntry {
            get {
                return ((string)(this["client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_" +
                    "project_timeAndExpense_input_projectTimecardWithRateAmtEntry_projectTimecardWith" +
                    "RateAmtEntry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/common.asmx")]
        public string client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_common_common {
            get {
                return ((string)(this["client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_" +
                    "common_common"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/projectMaintenance.asmx")]
        public string client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_project_projectController_maintenance_projectMaintenance_projectMaintenance {
            get {
                return ((string)(this["client_project_timeAndExpense_input_projectTimecardWithRateAmtEntry_ctDynamicsSL_" +
                    "project_projectController_maintenance_projectMaintenance_projectMaintenance"]));
            }
        }
    }
}
