//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.projectInvoiceAndAdjustmentMaintenance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/common.asmx")]
        public string client_projectInvoiceAndAdjustmentMaintenance_ctDynamicsSL_common_common {
            get {
                return ((string)(this["client_projectInvoiceAndAdjustmentMaintenance_ctDynamicsSL_common_common"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/projectInvoiceAndAdjustmentMaintenan" +
            "ce.asmx")]
        public string client_projectInvoiceAndAdjustmentMaintenance_ctDynamicsSL_project_flexibleBillings_input_projectInvoiceAndAdjustmentMaintenance_projectInvoiceAndAdjustmentMaintenance {
            get {
                return ((string)(this["client_projectInvoiceAndAdjustmentMaintenance_ctDynamicsSL_project_flexibleBillin" +
                    "gs_input_projectInvoiceAndAdjustmentMaintenance_projectInvoiceAndAdjustmentMaint" +
                    "enance"]));
            }
        }
    }
}
