//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.fieldService.serviceDispatch.maintenance.serviceEmployeeMaintenance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/serviceEmployeeMaintenance.asmx")]
        public string client_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_ctDynamicsSL_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_serviceEmployeeMaintenance {
            get {
                return ((string)(this["client_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_ctDyna" +
                    "micsSL_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_servi" +
                    "ceEmployeeMaintenance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ctDynamicsSL/common.asmx")]
        public string client_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_ctDynamicsSL_common_common {
            get {
                return ((string)(this["client_fieldService_serviceDispatch_maintenance_serviceEmployeeMaintenance_ctDyna" +
                    "micsSL_common_common"]));
            }
        }
    }
}
